package com.efida.sports.dmp.dao.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

@ApiModel(value = "日志信息")
public class OpenCallLogEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_call_log.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "日志ID")
    private Long    id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_call_log.seq_no
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "序列号ID")
    private String  seqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_call_log.unit_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "承办方账号")
    private String  unitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_call_log.interface_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "接口标识")
    private String  interfaceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_call_log.interface_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "接口名称")
    private String  interfaceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_call_log.request_ip
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "请求IP")
    private String  requestIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_call_log.request_param
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "请求参数(概要)")
    private String  requestParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_call_log.request_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "请求时间")
    private String  requestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_call_log.spent
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "耗费时间(ms)")
    private Integer spent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_call_log.success
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "是否成功:1 成功, 0失败")
    private Byte    success;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_call_log.status
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "状态描述")
    private String  status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_call_log.total
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "响应数据量")
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_call_log.gmt_create
     *
     * @mbggenerated
     */
    private Date    gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_call_log.gmt_modified
     *
     * @mbggenerated
     */
    private Date    gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_call_log.id
     *
     * @return the value of open_call_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_call_log.id
     *
     * @param id the value for open_call_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_call_log.seq_no
     *
     * @return the value of open_call_log.seq_no
     *
     * @mbggenerated
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_call_log.seq_no
     *
     * @param seqNo the value for open_call_log.seq_no
     *
     * @mbggenerated
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo == null ? null : seqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_call_log.unit_code
     *
     * @return the value of open_call_log.unit_code
     *
     * @mbggenerated
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_call_log.unit_code
     *
     * @param unitCode the value for open_call_log.unit_code
     *
     * @mbggenerated
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode == null ? null : unitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_call_log.interface_code
     *
     * @return the value of open_call_log.interface_code
     *
     * @mbggenerated
     */
    public String getInterfaceCode() {
        return interfaceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_call_log.interface_code
     *
     * @param interfaceCode the value for open_call_log.interface_code
     *
     * @mbggenerated
     */
    public void setInterfaceCode(String interfaceCode) {
        this.interfaceCode = interfaceCode == null ? null : interfaceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_call_log.interface_name
     *
     * @return the value of open_call_log.interface_name
     *
     * @mbggenerated
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_call_log.interface_name
     *
     * @param interfaceName the value for open_call_log.interface_name
     *
     * @mbggenerated
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName == null ? null : interfaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_call_log.request_ip
     *
     * @return the value of open_call_log.request_ip
     *
     * @mbggenerated
     */
    public String getRequestIp() {
        return requestIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_call_log.request_ip
     *
     * @param requestIp the value for open_call_log.request_ip
     *
     * @mbggenerated
     */
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp == null ? null : requestIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_call_log.request_param
     *
     * @return the value of open_call_log.request_param
     *
     * @mbggenerated
     */
    public String getRequestParam() {
        return requestParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_call_log.request_param
     *
     * @param requestParam the value for open_call_log.request_param
     *
     * @mbggenerated
     */
    public void setRequestParam(String requestParam) {
        this.requestParam = requestParam == null ? null : requestParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_call_log.request_time
     *
     * @return the value of open_call_log.request_time
     *
     * @mbggenerated
     */
    public String getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_call_log.request_time
     *
     * @param requestTime the value for open_call_log.request_time
     *
     * @mbggenerated
     */
    public void setRequestTime(String requestTime) {
        this.requestTime = requestTime == null ? null : requestTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_call_log.spent
     *
     * @return the value of open_call_log.spent
     *
     * @mbggenerated
     */
    public Integer getSpent() {
        return spent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_call_log.spent
     *
     * @param spent the value for open_call_log.spent
     *
     * @mbggenerated
     */
    public void setSpent(Integer spent) {
        this.spent = spent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_call_log.success
     *
     * @return the value of open_call_log.success
     *
     * @mbggenerated
     */
    public Byte getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_call_log.success
     *
     * @param success the value for open_call_log.success
     *
     * @mbggenerated
     */
    public void setSuccess(Byte success) {
        this.success = success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_call_log.status
     *
     * @return the value of open_call_log.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_call_log.status
     *
     * @param status the value for open_call_log.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_call_log.total
     *
     * @return the value of open_call_log.total
     *
     * @mbggenerated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_call_log.total
     *
     * @param total the value for open_call_log.total
     *
     * @mbggenerated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_call_log.gmt_create
     *
     * @return the value of open_call_log.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_call_log.gmt_create
     *
     * @param gmtCreate the value for open_call_log.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_call_log.gmt_modified
     *
     * @return the value of open_call_log.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_call_log.gmt_modified
     *
     * @param gmtModified the value for open_call_log.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}