package com.efida.sports.dmp.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

import cn.evake.auth.util.DateUtil;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "运动员成绩信息")
public class OpenScoreEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.id
     *
     * @mbggenerated
     */
    private Long       id;

    /**
     * 
     */
    @ApiModelProperty(value = "批次号")
    private String     batchNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.score_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "成绩编号")
    private String     scoreCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.unit_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "承办单位编号")
    private String     unitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.player_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "运动员编号")
    private String     playerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.player_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "运动员名称")
    private String     playerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.player_phone
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "运动员电话")
    private String     playerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.sex
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "m:男 f:女 o:其他")
    private String     sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.open_plat_type
     *
     * @mbggenerated
     */
    private String     openPlatType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.open_id
     *
     * @mbggenerated
     */
    private String     openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.game_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "项目编号")
    private String     gameCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.game_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "项目名称")
    private String     gameName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.match_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "赛事编号")
    private String     matchCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.match_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "赛事名称")
    private String     matchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.field_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "赛场编号")
    private String     fieldCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.field_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "赛场名称")
    private String     fieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.match_group_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "分组编号")
    private String     matchGroupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.match_group_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "分组名称")
    private String     matchGroupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.event_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "赛事项编号")
    private String     eventCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.event_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "赛事项名称")
    private String     eventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.part_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "参赛时间")
    private Date       partTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.score_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "科目名")
    private String     scoreName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.score
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "成绩")
    private BigDecimal score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.score_unit
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "成绩单位")
    private String     scoreUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.score_desc
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "成绩描述")
    private String     scoreDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.is_valid
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "1 有效 0 无效")
    private Byte       isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.score_type
     *
     * @mbggenerated
     */
    private String     scoreType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.score_prop
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "成绩相关属性(JSON数据)")
    private String     scoreProp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.player_prop
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "运动员相关属性(JSON数据)")
    private String     playerProp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.channel_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "渠道标识")
    private String     channelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.idempotent_id
     *
     * @mbggenerated
     */
    private String     idempotentId;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column open_apply_info.source
    *
    * @mbggenerated
    */
    private Byte       source;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column open_apply_info.sync
    *
    * @mbggenerated
    */
    private Byte       sync;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column open_apply_info.sync_total
    *
    * @mbggenerated
    */
    private Integer    syncTotal;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column open_apply_info.sync_status
    *
    * @mbggenerated
    */
    private String     syncStatus;

    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column open_apply_info.next_sync_time
    *
    * @mbggenerated
    */
    private Date       nextSyncTime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.gmt_create
     *
     * @mbggenerated
     */
    private Date       gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_score.gmt_modified
     *
     * @mbggenerated
     */
    private Date       gmtModified;

    /**
     * 报名渠道
     */
    @ApiModelProperty(value = "报名渠道（1 官网  2承办方）")
    private Integer    enrollSource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.id
     *
     * @return the value of open_score.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.id
     *
     * @param id the value for open_score.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.score_code
     *
     * @return the value of open_score.score_code
     *
     * @mbggenerated
     */
    public String getScoreCode() {
        return scoreCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.score_code
     *
     * @param scoreCode the value for open_score.score_code
     *
     * @mbggenerated
     */
    public void setScoreCode(String scoreCode) {
        this.scoreCode = scoreCode == null ? null : scoreCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.unit_code
     *
     * @return the value of open_score.unit_code
     *
     * @mbggenerated
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.unit_code
     *
     * @param unitCode the value for open_score.unit_code
     *
     * @mbggenerated
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode == null ? null : unitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.player_code
     *
     * @return the value of open_score.player_code
     *
     * @mbggenerated
     */
    public String getPlayerCode() {
        return playerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.player_code
     *
     * @param playerCode the value for open_score.player_code
     *
     * @mbggenerated
     */
    public void setPlayerCode(String playerCode) {
        this.playerCode = playerCode == null ? null : playerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.player_name
     *
     * @return the value of open_score.player_name
     *
     * @mbggenerated
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.player_name
     *
     * @param playerName the value for open_score.player_name
     *
     * @mbggenerated
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName == null ? null : playerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.player_phone
     *
     * @return the value of open_score.player_phone
     *
     * @mbggenerated
     */
    public String getPlayerPhone() {
        return playerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.player_phone
     *
     * @param playerPhone the value for open_score.player_phone
     *
     * @mbggenerated
     */
    public void setPlayerPhone(String playerPhone) {
        this.playerPhone = playerPhone == null ? null : playerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.sex
     *
     * @return the value of open_score.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.sex
     *
     * @param sex the value for open_score.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.open_plat_type
     *
     * @return the value of open_score.open_plat_type
     *
     * @mbggenerated
     */
    public String getOpenPlatType() {
        return openPlatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.open_plat_type
     *
     * @param openPlatType the value for open_score.open_plat_type
     *
     * @mbggenerated
     */
    public void setOpenPlatType(String openPlatType) {
        this.openPlatType = openPlatType == null ? null : openPlatType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.open_id
     *
     * @return the value of open_score.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.open_id
     *
     * @param openId the value for open_score.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.game_code
     *
     * @return the value of open_score.game_code
     *
     * @mbggenerated
     */
    public String getGameCode() {
        return gameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.game_code
     *
     * @param gameCode the value for open_score.game_code
     *
     * @mbggenerated
     */
    public void setGameCode(String gameCode) {
        this.gameCode = gameCode == null ? null : gameCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.game_name
     *
     * @return the value of open_score.game_name
     *
     * @mbggenerated
     */
    public String getGameName() {
        return gameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.game_name
     *
     * @param gameName the value for open_score.game_name
     *
     * @mbggenerated
     */
    public void setGameName(String gameName) {
        this.gameName = gameName == null ? null : gameName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.match_code
     *
     * @return the value of open_score.match_code
     *
     * @mbggenerated
     */
    public String getMatchCode() {
        return matchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.match_code
     *
     * @param matchCode the value for open_score.match_code
     *
     * @mbggenerated
     */
    public void setMatchCode(String matchCode) {
        this.matchCode = matchCode == null ? null : matchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.match_name
     *
     * @return the value of open_score.match_name
     *
     * @mbggenerated
     */
    public String getMatchName() {
        return matchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.match_name
     *
     * @param matchName the value for open_score.match_name
     *
     * @mbggenerated
     */
    public void setMatchName(String matchName) {
        this.matchName = matchName == null ? null : matchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.field_code
     *
     * @return the value of open_score.field_code
     *
     * @mbggenerated
     */
    public String getFieldCode() {
        return fieldCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.field_code
     *
     * @param fieldCode the value for open_score.field_code
     *
     * @mbggenerated
     */
    public void setFieldCode(String fieldCode) {
        this.fieldCode = fieldCode == null ? null : fieldCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.field_name
     *
     * @return the value of open_score.field_name
     *
     * @mbggenerated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.field_name
     *
     * @param fieldName the value for open_score.field_name
     *
     * @mbggenerated
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.match_group_code
     *
     * @return the value of open_score.match_group_code
     *
     * @mbggenerated
     */
    public String getMatchGroupCode() {
        return matchGroupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.match_group_code
     *
     * @param matchGroupCode the value for open_score.match_group_code
     *
     * @mbggenerated
     */
    public void setMatchGroupCode(String matchGroupCode) {
        this.matchGroupCode = matchGroupCode == null ? null : matchGroupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.match_group_name
     *
     * @return the value of open_score.match_group_name
     *
     * @mbggenerated
     */
    public String getMatchGroupName() {
        return matchGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.match_group_name
     *
     * @param matchGroupName the value for open_score.match_group_name
     *
     * @mbggenerated
     */
    public void setMatchGroupName(String matchGroupName) {
        this.matchGroupName = matchGroupName == null ? null : matchGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.event_code
     *
     * @return the value of open_score.event_code
     *
     * @mbggenerated
     */
    public String getEventCode() {
        return eventCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.event_code
     *
     * @param eventCode the value for open_score.event_code
     *
     * @mbggenerated
     */
    public void setEventCode(String eventCode) {
        this.eventCode = eventCode == null ? null : eventCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.event_name
     *
     * @return the value of open_score.event_name
     *
     * @mbggenerated
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.event_name
     *
     * @param eventName the value for open_score.event_name
     *
     * @mbggenerated
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.part_time
     *
     * @return the value of open_score.part_time
     *
     * @mbggenerated
     */
    public Date getPartTime() {
        return partTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.part_time
     *
     * @param partTime the value for open_score.part_time
     *
     * @mbggenerated
     */
    public void setPartTime(Date partTime) {
        this.partTime = partTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.score_name
     *
     * @return the value of open_score.score_name
     *
     * @mbggenerated
     */
    public String getScoreName() {
        return scoreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.score_name
     *
     * @param scoreName the value for open_score.score_name
     *
     * @mbggenerated
     */
    public void setScoreName(String scoreName) {
        this.scoreName = scoreName == null ? null : scoreName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.score
     *
     * @return the value of open_score.score
     *
     * @mbggenerated
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.score
     *
     * @param score the value for open_score.score
     *
     * @mbggenerated
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.score_unit
     *
     * @return the value of open_score.score_unit
     *
     * @mbggenerated
     */
    public String getScoreUnit() {
        return scoreUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.score_unit
     *
     * @param scoreUnit the value for open_score.score_unit
     *
     * @mbggenerated
     */
    public void setScoreUnit(String scoreUnit) {
        this.scoreUnit = scoreUnit == null ? null : scoreUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.score_desc
     *
     * @return the value of open_score.score_desc
     *
     * @mbggenerated
     */
    public String getScoreDesc() {
        return scoreDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.score_desc
     *
     * @param scoreDesc the value for open_score.score_desc
     *
     * @mbggenerated
     */
    public void setScoreDesc(String scoreDesc) {
        this.scoreDesc = scoreDesc == null ? null : scoreDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.is_valid
     *
     * @return the value of open_score.is_valid
     *
     * @mbggenerated
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.is_valid
     *
     * @param isValid the value for open_score.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.score_type
     *
     * @return the value of open_score.score_type
     *
     * @mbggenerated
     */
    public String getScoreType() {
        return scoreType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.score_type
     *
     * @param scoreType the value for open_score.score_type
     *
     * @mbggenerated
     */
    public void setScoreType(String scoreType) {
        this.scoreType = scoreType == null ? null : scoreType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.score_prop
     *
     * @return the value of open_score.score_prop
     *
     * @mbggenerated
     */
    public String getScoreProp() {
        return scoreProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.score_prop
     *
     * @param scoreProp the value for open_score.score_prop
     *
     * @mbggenerated
     */
    public void setScoreProp(String scoreProp) {
        this.scoreProp = scoreProp == null ? null : scoreProp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.player_prop
     *
     * @return the value of open_score.player_prop
     *
     * @mbggenerated
     */
    public String getPlayerProp() {
        return playerProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.player_prop
     *
     * @param playerProp the value for open_score.player_prop
     *
     * @mbggenerated
     */
    public void setPlayerProp(String playerProp) {
        this.playerProp = playerProp == null ? null : playerProp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.channel_code
     *
     * @return the value of open_score.channel_code
     *
     * @mbggenerated
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.channel_code
     *
     * @param channelCode the value for open_score.channel_code
     *
     * @mbggenerated
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.idempotent_id
     *
     * @return the value of open_score.idempotent_id
     *
     * @mbggenerated
     */
    public String getIdempotentId() {
        return idempotentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.idempotent_id
     *
     * @param idempotentId the value for open_score.idempotent_id
     *
     * @mbggenerated
     */
    public void setIdempotentId(String idempotentId) {
        this.idempotentId = idempotentId == null ? null : idempotentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.gmt_create
     *
     * @return the value of open_score.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.gmt_create
     *
     * @param gmtCreate the value for open_score.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_score.gmt_modified
     *
     * @return the value of open_score.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_score.gmt_modified
     *
     * @param gmtModified the value for open_score.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * 参赛时间
     * @title
     * @methodName
     * @author wangyi
     * @description
     * @return
     */
    public String getPartTimeStr() {
        return getPartTime() == null ? null
            : DateUtil.formatDate(getPartTime(), DateUtil.WEB_FORMAT);
    }

    /**
     * 数据创建时间
     * @title
     * @methodName
     * @author wangyi
     * @description
     * @return
     */
    public String getGmtCreateStr() {
        return gmtCreate == null ? null : DateUtil.formatDate(gmtCreate);
    }

    public Byte getSource() {
        return source;
    }

    public void setSource(Byte source) {
        this.source = source;
    }

    public Byte getSync() {
        return sync;
    }

    public void setSync(Byte sync) {
        this.sync = sync;
    }

    public Integer getSyncTotal() {
        return syncTotal;
    }

    public void setSyncTotal(Integer syncTotal) {
        this.syncTotal = syncTotal;
    }

    public String getSyncStatus() {
        return syncStatus;
    }

    public void setSyncStatus(String syncStatus) {
        this.syncStatus = syncStatus;
    }

    public Date getNextSyncTime() {
        return nextSyncTime;
    }

    public void setNextSyncTime(Date nextSyncTime) {
        this.nextSyncTime = nextSyncTime;
    }

    public String getBatchNumber() {
        return batchNumber;
    }

    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber;
    }

    public Integer getEnrollSource() {
        return enrollSource;
    }

    public void setEnrollSource(Integer enrollSource) {
        this.enrollSource = enrollSource;
    }

}