package com.efida.sports.dmp.dao.entity;

import java.util.Date;

public class OpenLogContentEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_log_content.id
     *
     * @mbggenerated
     */
    private Long   id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_log_content.seq_no
     *
     * @mbggenerated
     */
    private String seqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_log_content.gmt_create
     *
     * @mbggenerated
     */
    private Date   gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_log_content.gmt_modified
     *
     * @mbggenerated
     */
    private Date   gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_log_content.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_log_content.id
     *
     * @return the value of open_log_content.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_log_content.id
     *
     * @param id the value for open_log_content.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_log_content.seq_no
     *
     * @return the value of open_log_content.seq_no
     *
     * @mbggenerated
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_log_content.seq_no
     *
     * @param seqNo the value for open_log_content.seq_no
     *
     * @mbggenerated
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo == null ? null : seqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_log_content.gmt_create
     *
     * @return the value of open_log_content.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_log_content.gmt_create
     *
     * @param gmtCreate the value for open_log_content.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_log_content.gmt_modified
     *
     * @return the value of open_log_content.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_log_content.gmt_modified
     *
     * @param gmtModified the value for open_log_content.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_log_content.content
     *
     * @return the value of open_log_content.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_log_content.content
     *
     * @param content the value for open_log_content.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}