package com.efida.sports.dmp.dao.entity;

import java.util.Date;

public class OpenApplyInfoEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.id
     *
     * @mbggenerated
     */
    private Long    id;

    /**
     * 批次号
     */
    private String  batchNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.apply_time
     *
     * @mbggenerated
     */
    private Date    applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.apply_code
     *
     * @mbggenerated
     */
    private String  applyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.leader_name
     *
     * @mbggenerated
     */
    private String  leaderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.leader_phone
     *
     * @mbggenerated
     */
    private String  leaderPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.term_name
     *
     * @mbggenerated
     */
    private String  teamName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.event_type
     *
     * @mbggenerated
     */
    private String  eventType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.registration_num
     *
     * @mbggenerated
     */
    private Integer registrationNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.apply_amount
     *
     * @mbggenerated
     */
    private Long    applyAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.apply_status
     *
     * @mbggenerated
     */
    private String  applyStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.unit_code
     *
     * @mbggenerated
     */
    private String  unitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.game_code
     *
     * @mbggenerated
     */
    private String  gameCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.game_name
     *
     * @mbggenerated
     */
    private String  gameName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.match_code
     *
     * @mbggenerated
     */
    private String  matchCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.match_name
     *
     * @mbggenerated
     */
    private String  matchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.field_code
     *
     * @mbggenerated
     */
    private String  fieldCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.field_name
     *
     * @mbggenerated
     */
    private String  fieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.match_group_name
     *
     * @mbggenerated
     */
    private String  matchGroupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.match_group_code
     *
     * @mbggenerated
     */
    private String  matchGroupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.event_code
     *
     * @mbggenerated
     */
    private String  eventCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.event_name
     *
     * @mbggenerated
     */
    private String  eventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.event_start_time
     *
     * @mbggenerated
     */
    private Date    eventStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.event_end_time
     *
     * @mbggenerated
     */
    private Date    eventEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.is_delet
     *
     * @mbggenerated
     */
    private Byte    isDelet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.expire_time
     *
     * @mbggenerated
     */
    private Date    expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.channel_code
     *
     * @mbggenerated
     */
    private String  channelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.idempotent_id
     *
     * @mbggenerated
     */
    private String  idempotentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.source
     *
     * @mbggenerated
     */
    private Byte    source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.sync
     *
     * @mbggenerated
     */
    private Byte    sync;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.sync_total
     *
     * @mbggenerated
     */
    private Integer syncTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.sync_status
     *
     * @mbggenerated
     */
    private String  syncStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.next_sync_time
     *
     * @mbggenerated
     */
    private Date    nextSyncTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.gmt_create
     *
     * @mbggenerated
     */
    private Date    gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.gmt_modified
     *
     * @mbggenerated
     */
    private Date    gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.id
     *
     * @return the value of open_apply_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.id
     *
     * @param id the value for open_apply_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.apply_time
     *
     * @return the value of open_apply_info.apply_time
     *
     * @mbggenerated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.apply_time
     *
     * @param applyTime the value for open_apply_info.apply_time
     *
     * @mbggenerated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.apply_code
     *
     * @return the value of open_apply_info.apply_code
     *
     * @mbggenerated
     */
    public String getApplyCode() {
        return applyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.apply_code
     *
     * @param applyCode the value for open_apply_info.apply_code
     *
     * @mbggenerated
     */
    public void setApplyCode(String applyCode) {
        this.applyCode = applyCode == null ? null : applyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.leader_name
     *
     * @return the value of open_apply_info.leader_name
     *
     * @mbggenerated
     */
    public String getLeaderName() {
        return leaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.leader_name
     *
     * @param leaderName the value for open_apply_info.leader_name
     *
     * @mbggenerated
     */
    public void setLeaderName(String leaderName) {
        this.leaderName = leaderName == null ? null : leaderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.leader_phone
     *
     * @return the value of open_apply_info.leader_phone
     *
     * @mbggenerated
     */
    public String getLeaderPhone() {
        return leaderPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.leader_phone
     *
     * @param leaderPhone the value for open_apply_info.leader_phone
     *
     * @mbggenerated
     */
    public void setLeaderPhone(String leaderPhone) {
        this.leaderPhone = leaderPhone == null ? null : leaderPhone.trim();
    }

    public String getTeamName() {
        return teamName;
    }

    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.event_type
     *
     * @return the value of open_apply_info.event_type
     *
     * @mbggenerated
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.event_type
     *
     * @param eventType the value for open_apply_info.event_type
     *
     * @mbggenerated
     */
    public void setEventType(String eventType) {
        this.eventType = eventType == null ? null : eventType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.registration_num
     *
     * @return the value of open_apply_info.registration_num
     *
     * @mbggenerated
     */
    public Integer getRegistrationNum() {
        return registrationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.registration_num
     *
     * @param registrationNum the value for open_apply_info.registration_num
     *
     * @mbggenerated
     */
    public void setRegistrationNum(Integer registrationNum) {
        this.registrationNum = registrationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.apply_amount
     *
     * @return the value of open_apply_info.apply_amount
     *
     * @mbggenerated
     */
    public Long getApplyAmount() {
        return applyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.apply_amount
     *
     * @param applyAmount the value for open_apply_info.apply_amount
     *
     * @mbggenerated
     */
    public void setApplyAmount(Long applyAmount) {
        this.applyAmount = applyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.apply_status
     *
     * @return the value of open_apply_info.apply_status
     *
     * @mbggenerated
     */
    public String getApplyStatus() {
        return applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.apply_status
     *
     * @param applyStatus the value for open_apply_info.apply_status
     *
     * @mbggenerated
     */
    public void setApplyStatus(String applyStatus) {
        this.applyStatus = applyStatus == null ? null : applyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.unit_code
     *
     * @return the value of open_apply_info.unit_code
     *
     * @mbggenerated
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.unit_code
     *
     * @param unitCode the value for open_apply_info.unit_code
     *
     * @mbggenerated
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode == null ? null : unitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.game_code
     *
     * @return the value of open_apply_info.game_code
     *
     * @mbggenerated
     */
    public String getGameCode() {
        return gameCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.game_code
     *
     * @param gameCode the value for open_apply_info.game_code
     *
     * @mbggenerated
     */
    public void setGameCode(String gameCode) {
        this.gameCode = gameCode == null ? null : gameCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.game_name
     *
     * @return the value of open_apply_info.game_name
     *
     * @mbggenerated
     */
    public String getGameName() {
        return gameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.game_name
     *
     * @param gameName the value for open_apply_info.game_name
     *
     * @mbggenerated
     */
    public void setGameName(String gameName) {
        this.gameName = gameName == null ? null : gameName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.match_code
     *
     * @return the value of open_apply_info.match_code
     *
     * @mbggenerated
     */
    public String getMatchCode() {
        return matchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.match_code
     *
     * @param matchCode the value for open_apply_info.match_code
     *
     * @mbggenerated
     */
    public void setMatchCode(String matchCode) {
        this.matchCode = matchCode == null ? null : matchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.match_name
     *
     * @return the value of open_apply_info.match_name
     *
     * @mbggenerated
     */
    public String getMatchName() {
        return matchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.match_name
     *
     * @param matchName the value for open_apply_info.match_name
     *
     * @mbggenerated
     */
    public void setMatchName(String matchName) {
        this.matchName = matchName == null ? null : matchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.field_code
     *
     * @return the value of open_apply_info.field_code
     *
     * @mbggenerated
     */
    public String getFieldCode() {
        return fieldCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.field_code
     *
     * @param fieldCode the value for open_apply_info.field_code
     *
     * @mbggenerated
     */
    public void setFieldCode(String fieldCode) {
        this.fieldCode = fieldCode == null ? null : fieldCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.field_name
     *
     * @return the value of open_apply_info.field_name
     *
     * @mbggenerated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.field_name
     *
     * @param fieldName the value for open_apply_info.field_name
     *
     * @mbggenerated
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.match_group_name
     *
     * @return the value of open_apply_info.match_group_name
     *
     * @mbggenerated
     */
    public String getMatchGroupName() {
        return matchGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.match_group_name
     *
     * @param matchGroupName the value for open_apply_info.match_group_name
     *
     * @mbggenerated
     */
    public void setMatchGroupName(String matchGroupName) {
        this.matchGroupName = matchGroupName == null ? null : matchGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.match_group_code
     *
     * @return the value of open_apply_info.match_group_code
     *
     * @mbggenerated
     */
    public String getMatchGroupCode() {
        return matchGroupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.match_group_code
     *
     * @param matchGroupCode the value for open_apply_info.match_group_code
     *
     * @mbggenerated
     */
    public void setMatchGroupCode(String matchGroupCode) {
        this.matchGroupCode = matchGroupCode == null ? null : matchGroupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.event_code
     *
     * @return the value of open_apply_info.event_code
     *
     * @mbggenerated
     */
    public String getEventCode() {
        return eventCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.event_code
     *
     * @param eventCode the value for open_apply_info.event_code
     *
     * @mbggenerated
     */
    public void setEventCode(String eventCode) {
        this.eventCode = eventCode == null ? null : eventCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.event_name
     *
     * @return the value of open_apply_info.event_name
     *
     * @mbggenerated
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.event_name
     *
     * @param eventName the value for open_apply_info.event_name
     *
     * @mbggenerated
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.event_start_time
     *
     * @return the value of open_apply_info.event_start_time
     *
     * @mbggenerated
     */
    public Date getEventStartTime() {
        return eventStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.event_start_time
     *
     * @param eventStartTime the value for open_apply_info.event_start_time
     *
     * @mbggenerated
     */
    public void setEventStartTime(Date eventStartTime) {
        this.eventStartTime = eventStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.event_end_time
     *
     * @return the value of open_apply_info.event_end_time
     *
     * @mbggenerated
     */
    public Date getEventEndTime() {
        return eventEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.event_end_time
     *
     * @param eventEndTime the value for open_apply_info.event_end_time
     *
     * @mbggenerated
     */
    public void setEventEndTime(Date eventEndTime) {
        this.eventEndTime = eventEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.is_delet
     *
     * @return the value of open_apply_info.is_delet
     *
     * @mbggenerated
     */
    public Byte getIsDelet() {
        return isDelet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.is_delet
     *
     * @param isDelet the value for open_apply_info.is_delet
     *
     * @mbggenerated
     */
    public void setIsDelet(Byte isDelet) {
        this.isDelet = isDelet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.expire_time
     *
     * @return the value of open_apply_info.expire_time
     *
     * @mbggenerated
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.expire_time
     *
     * @param expireTime the value for open_apply_info.expire_time
     *
     * @mbggenerated
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.channel_code
     *
     * @return the value of open_apply_info.channel_code
     *
     * @mbggenerated
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.channel_code
     *
     * @param channelCode the value for open_apply_info.channel_code
     *
     * @mbggenerated
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.idempotent_id
     *
     * @return the value of open_apply_info.idempotent_id
     *
     * @mbggenerated
     */
    public String getIdempotentId() {
        return idempotentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.idempotent_id
     *
     * @param idempotentId the value for open_apply_info.idempotent_id
     *
     * @mbggenerated
     */
    public void setIdempotentId(String idempotentId) {
        this.idempotentId = idempotentId == null ? null : idempotentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.source
     *
     * @return the value of open_apply_info.source
     *
     * @mbggenerated
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.source
     *
     * @param source the value for open_apply_info.source
     *
     * @mbggenerated
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.sync
     *
     * @return the value of open_apply_info.sync
     *
     * @mbggenerated
     */
    public Byte getSync() {
        return sync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.sync
     *
     * @param sync the value for open_apply_info.sync
     *
     * @mbggenerated
     */
    public void setSync(Byte sync) {
        this.sync = sync;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.sync_total
     *
     * @return the value of open_apply_info.sync_total
     *
     * @mbggenerated
     */
    public Integer getSyncTotal() {
        return syncTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.sync_total
     *
     * @param syncTotal the value for open_apply_info.sync_total
     *
     * @mbggenerated
     */
    public void setSyncTotal(Integer syncTotal) {
        this.syncTotal = syncTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.sync_status
     *
     * @return the value of open_apply_info.sync_status
     *
     * @mbggenerated
     */
    public String getSyncStatus() {
        return syncStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.sync_status
     *
     * @param syncStatus the value for open_apply_info.sync_status
     *
     * @mbggenerated
     */
    public void setSyncStatus(String syncStatus) {
        this.syncStatus = syncStatus == null ? null : syncStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.next_sync_time
     *
     * @return the value of open_apply_info.next_sync_time
     *
     * @mbggenerated
     */
    public Date getNextSyncTime() {
        return nextSyncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.next_sync_time
     *
     * @param nextSyncTime the value for open_apply_info.next_sync_time
     *
     * @mbggenerated
     */
    public void setNextSyncTime(Date nextSyncTime) {
        this.nextSyncTime = nextSyncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.gmt_create
     *
     * @return the value of open_apply_info.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.gmt_create
     *
     * @param gmtCreate the value for open_apply_info.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_apply_info.gmt_modified
     *
     * @return the value of open_apply_info.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_apply_info.gmt_modified
     *
     * @param gmtModified the value for open_apply_info.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getBatchNumber() {
        return batchNumber;
    }

    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber;
    }
}