package com.efida.sports.dmp.dao.entity;

import java.util.Date;

public class OpenPlayerEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.id
     *
     * @mbggenerated
     */
    private Long    id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_code
     *
     * @mbggenerated
     */
    private String  playerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.apply_code
     *
     * @mbggenerated
     */
    private String  applyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_no
     *
     * @mbggenerated
     */
    private Integer playerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_phone
     *
     * @mbggenerated
     */
    private String  playerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_name
     *
     * @mbggenerated
     */
    private String  playerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.sex
     *
     * @mbggenerated
     */
    private String  sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.register_code
     *
     * @mbggenerated
     */
    private String  registerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.email
     *
     * @mbggenerated
     */
    private String  email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_height
     *
     * @mbggenerated
     */
    private Integer playerHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_weight
     *
     * @mbggenerated
     */
    private Double  playerWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_birth
     *
     * @mbggenerated
     */
    private Date    playerBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_nationality
     *
     * @mbggenerated
     */
    private String  playerNationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_work_unit
     *
     * @mbggenerated
     */
    private String  playerWorkUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_address
     *
     * @mbggenerated
     */
    private String  playerAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_cer_type
     *
     * @mbggenerated
     */
    private String  playerCerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_cer_no
     *
     * @mbggenerated
     */
    private String  playerCerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_blood_type
     *
     * @mbggenerated
     */
    private String  playerBloodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_nation
     *
     * @mbggenerated
     */
    private String  playerNation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_cloth_size
     *
     * @mbggenerated
     */
    private String  playerClothSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_emergency_name
     *
     * @mbggenerated
     */
    private String  playerEmergencyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_emergency_phone
     *
     * @mbggenerated
     */
    private String  playerEmergencyPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.att_url
     *
     * @mbggenerated
     */
    private String  attUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.img_url
     *
     * @mbggenerated
     */
    private String  imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.player_category
     *
     * @mbggenerated
     */
    private String  playerCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.open_plat_type
     *
     * @mbggenerated
     */
    private String  openPlatType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.open_id
     *
     * @mbggenerated
     */
    private String  openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.ext_prop
     *
     * @mbggenerated
     */
    private String  extProp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.is_delete
     *
     * @mbggenerated
     */
    private Byte    isDelete;
    /**
     * 是否已清洗
     */
    private Byte    isClean;
    /**
     * 报名终端类型
     */
    private String  terminal;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.gmt_create
     *
     * @mbggenerated
     */
    private Date    gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_player.gmt_modified
     *
     * @mbggenerated
     */
    private Date    gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.id
     *
     * @return the value of open_player.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.id
     *
     * @param id the value for open_player.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_code
     *
     * @return the value of open_player.player_code
     *
     * @mbggenerated
     */
    public String getPlayerCode() {
        return playerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_code
     *
     * @param playerCode the value for open_player.player_code
     *
     * @mbggenerated
     */
    public void setPlayerCode(String playerCode) {
        this.playerCode = playerCode == null ? null : playerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.apply_code
     *
     * @return the value of open_player.apply_code
     *
     * @mbggenerated
     */
    public String getApplyCode() {
        return applyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.apply_code
     *
     * @param applyCode the value for open_player.apply_code
     *
     * @mbggenerated
     */
    public void setApplyCode(String applyCode) {
        this.applyCode = applyCode == null ? null : applyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_no
     *
     * @return the value of open_player.player_no
     *
     * @mbggenerated
     */
    public Integer getPlayerNo() {
        return playerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_no
     *
     * @param playerNo the value for open_player.player_no
     *
     * @mbggenerated
     */
    public void setPlayerNo(Integer playerNo) {
        this.playerNo = playerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_phone
     *
     * @return the value of open_player.player_phone
     *
     * @mbggenerated
     */
    public String getPlayerPhone() {
        return playerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_phone
     *
     * @param playerPhone the value for open_player.player_phone
     *
     * @mbggenerated
     */
    public void setPlayerPhone(String playerPhone) {
        this.playerPhone = playerPhone == null ? null : playerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_name
     *
     * @return the value of open_player.player_name
     *
     * @mbggenerated
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_name
     *
     * @param playerName the value for open_player.player_name
     *
     * @mbggenerated
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName == null ? null : playerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.sex
     *
     * @return the value of open_player.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.sex
     *
     * @param sex the value for open_player.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.register_code
     *
     * @return the value of open_player.register_code
     *
     * @mbggenerated
     */
    public String getRegisterCode() {
        return registerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.register_code
     *
     * @param registerCode the value for open_player.register_code
     *
     * @mbggenerated
     */
    public void setRegisterCode(String registerCode) {
        this.registerCode = registerCode == null ? null : registerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.email
     *
     * @return the value of open_player.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.email
     *
     * @param email the value for open_player.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_height
     *
     * @return the value of open_player.player_height
     *
     * @mbggenerated
     */
    public Integer getPlayerHeight() {
        return playerHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_height
     *
     * @param playerHeight the value for open_player.player_height
     *
     * @mbggenerated
     */
    public void setPlayerHeight(Integer playerHeight) {
        this.playerHeight = playerHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_weight
     *
     * @return the value of open_player.player_weight
     *
     * @mbggenerated
     */
    public Double getPlayerWeight() {
        return playerWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_weight
     *
     * @param playerWeight the value for open_player.player_weight
     *
     * @mbggenerated
     */
    public void setPlayerWeight(Double playerWeight) {
        this.playerWeight = playerWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_birth
     *
     * @return the value of open_player.player_birth
     *
     * @mbggenerated
     */
    public Date getPlayerBirth() {
        return playerBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_birth
     *
     * @param playerBirth the value for open_player.player_birth
     *
     * @mbggenerated
     */
    public void setPlayerBirth(Date playerBirth) {
        this.playerBirth = playerBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_nationality
     *
     * @return the value of open_player.player_nationality
     *
     * @mbggenerated
     */
    public String getPlayerNationality() {
        return playerNationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_nationality
     *
     * @param playerNationality the value for open_player.player_nationality
     *
     * @mbggenerated
     */
    public void setPlayerNationality(String playerNationality) {
        this.playerNationality = playerNationality == null ? null : playerNationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_work_unit
     *
     * @return the value of open_player.player_work_unit
     *
     * @mbggenerated
     */
    public String getPlayerWorkUnit() {
        return playerWorkUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_work_unit
     *
     * @param playerWorkUnit the value for open_player.player_work_unit
     *
     * @mbggenerated
     */
    public void setPlayerWorkUnit(String playerWorkUnit) {
        this.playerWorkUnit = playerWorkUnit == null ? null : playerWorkUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_address
     *
     * @return the value of open_player.player_address
     *
     * @mbggenerated
     */
    public String getPlayerAddress() {
        return playerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_address
     *
     * @param playerAddress the value for open_player.player_address
     *
     * @mbggenerated
     */
    public void setPlayerAddress(String playerAddress) {
        this.playerAddress = playerAddress == null ? null : playerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_cer_type
     *
     * @return the value of open_player.player_cer_type
     *
     * @mbggenerated
     */
    public String getPlayerCerType() {
        return playerCerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_cer_type
     *
     * @param playerCerType the value for open_player.player_cer_type
     *
     * @mbggenerated
     */
    public void setPlayerCerType(String playerCerType) {
        this.playerCerType = playerCerType == null ? null : playerCerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_cer_no
     *
     * @return the value of open_player.player_cer_no
     *
     * @mbggenerated
     */
    public String getPlayerCerNo() {
        return playerCerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_cer_no
     *
     * @param playerCerNo the value for open_player.player_cer_no
     *
     * @mbggenerated
     */
    public void setPlayerCerNo(String playerCerNo) {
        this.playerCerNo = playerCerNo == null ? null : playerCerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_blood_type
     *
     * @return the value of open_player.player_blood_type
     *
     * @mbggenerated
     */
    public String getPlayerBloodType() {
        return playerBloodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_blood_type
     *
     * @param playerBloodType the value for open_player.player_blood_type
     *
     * @mbggenerated
     */
    public void setPlayerBloodType(String playerBloodType) {
        this.playerBloodType = playerBloodType == null ? null : playerBloodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_nation
     *
     * @return the value of open_player.player_nation
     *
     * @mbggenerated
     */
    public String getPlayerNation() {
        return playerNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_nation
     *
     * @param playerNation the value for open_player.player_nation
     *
     * @mbggenerated
     */
    public void setPlayerNation(String playerNation) {
        this.playerNation = playerNation == null ? null : playerNation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_cloth_size
     *
     * @return the value of open_player.player_cloth_size
     *
     * @mbggenerated
     */
    public String getPlayerClothSize() {
        return playerClothSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_cloth_size
     *
     * @param playerClothSize the value for open_player.player_cloth_size
     *
     * @mbggenerated
     */
    public void setPlayerClothSize(String playerClothSize) {
        this.playerClothSize = playerClothSize == null ? null : playerClothSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_emergency_name
     *
     * @return the value of open_player.player_emergency_name
     *
     * @mbggenerated
     */
    public String getPlayerEmergencyName() {
        return playerEmergencyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_emergency_name
     *
     * @param playerEmergencyName the value for open_player.player_emergency_name
     *
     * @mbggenerated
     */
    public void setPlayerEmergencyName(String playerEmergencyName) {
        this.playerEmergencyName = playerEmergencyName == null ? null : playerEmergencyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_emergency_phone
     *
     * @return the value of open_player.player_emergency_phone
     *
     * @mbggenerated
     */
    public String getPlayerEmergencyPhone() {
        return playerEmergencyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_emergency_phone
     *
     * @param playerEmergencyPhone the value for open_player.player_emergency_phone
     *
     * @mbggenerated
     */
    public void setPlayerEmergencyPhone(String playerEmergencyPhone) {
        this.playerEmergencyPhone = playerEmergencyPhone == null ? null
            : playerEmergencyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.att_url
     *
     * @return the value of open_player.att_url
     *
     * @mbggenerated
     */
    public String getAttUrl() {
        return attUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.att_url
     *
     * @param attUrl the value for open_player.att_url
     *
     * @mbggenerated
     */
    public void setAttUrl(String attUrl) {
        this.attUrl = attUrl == null ? null : attUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.img_url
     *
     * @return the value of open_player.img_url
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.img_url
     *
     * @param imgUrl the value for open_player.img_url
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.player_category
     *
     * @return the value of open_player.player_category
     *
     * @mbggenerated
     */
    public String getPlayerCategory() {
        return playerCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.player_category
     *
     * @param playerCategory the value for open_player.player_category
     *
     * @mbggenerated
     */
    public void setPlayerCategory(String playerCategory) {
        this.playerCategory = playerCategory == null ? null : playerCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.open_plat_type
     *
     * @return the value of open_player.open_plat_type
     *
     * @mbggenerated
     */
    public String getOpenPlatType() {
        return openPlatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.open_plat_type
     *
     * @param openPlatType the value for open_player.open_plat_type
     *
     * @mbggenerated
     */
    public void setOpenPlatType(String openPlatType) {
        this.openPlatType = openPlatType == null ? null : openPlatType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.open_id
     *
     * @return the value of open_player.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.open_id
     *
     * @param openId the value for open_player.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.ext_prop
     *
     * @return the value of open_player.ext_prop
     *
     * @mbggenerated
     */
    public String getExtProp() {
        return extProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.ext_prop
     *
     * @param extProp the value for open_player.ext_prop
     *
     * @mbggenerated
     */
    public void setExtProp(String extProp) {
        this.extProp = extProp == null ? null : extProp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.is_delete
     *
     * @return the value of open_player.is_delete
     *
     * @mbggenerated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.is_delete
     *
     * @param isDelete the value for open_player.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.gmt_create
     *
     * @return the value of open_player.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.gmt_create
     *
     * @param gmtCreate the value for open_player.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_player.gmt_modified
     *
     * @return the value of open_player.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_player.gmt_modified
     *
     * @param gmtModified the value for open_player.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public Byte getIsClean() {
        return isClean;
    }

    public void setIsClean(Byte isClean) {
        this.isClean = isClean;
    }

    public String getTerminal() {
        return terminal;
    }

    public void setTerminal(String terminal) {
        this.terminal = terminal;
    }

}