package com.efida.sports.dmp.dao.entity;

import java.util.Date;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "承办方账号")
public class OpenUnitEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_unit_account.id
     *
     * @mbggenerated
     */
    private Long    id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_unit_account.unit_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "承办方编号")
    private String  unitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_unit_account.unit_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "承办方名称")
    private String  unitName;

    /**
     * 联系人
     */
    @ApiModelProperty(value = "承办方联系人")
    private String  contact;

    /**
     * 联系电话
     */
    @ApiModelProperty(value = "承办方联系电")
    private String  phone;

    /**
     * 联系邮箱
     */
    @ApiModelProperty(value = "承办邮箱")
    private String  email;

    /**
     * 联系地址
     */
    @ApiModelProperty(value = "承办联系地址")
    private String  address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_unit_account.client_secrect
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "承办方秘钥")
    private String  clientSecrect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_unit_account.is_lock
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "承办方账户状态")
    private Byte    isLock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_unit_account.white_ip
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "承办方白名单")
    private String  whiteIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_unit_account.max_per_minute
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "承办方每分钟最大调用次数")
    private Integer maxPerMinute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_unit_account.remark
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "承办方备注")
    private String  remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_unit_account.gmt_create
     *
     * @mbggenerated
     */
    private Date    gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_unit_account.gmt_modified
     *
     * @mbggenerated
     */
    private Date    gmtModified;

    //////////////////////拓展字段///////////////////////////////

    @ApiModelProperty(value = "承办方管理密码")
    private String  managerPass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_unit_account.id
     *
     * @return the value of open_unit_account.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_unit_account.id
     *
     * @param id the value for open_unit_account.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_unit_account.unit_code
     *
     * @return the value of open_unit_account.unit_code
     *
     * @mbggenerated
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_unit_account.unit_code
     *
     * @param unitCode the value for open_unit_account.unit_code
     *
     * @mbggenerated
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode == null ? null : unitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_unit_account.unit_name
     *
     * @return the value of open_unit_account.unit_name
     *
     * @mbggenerated
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_unit_account.unit_name
     *
     * @param unitName the value for open_unit_account.unit_name
     *
     * @mbggenerated
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_unit_account.client_secrect
     *
     * @return the value of open_unit_account.client_secrect
     *
     * @mbggenerated
     */
    public String getClientSecrect() {
        return clientSecrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_unit_account.client_secrect
     *
     * @param clientSecrect the value for open_unit_account.client_secrect
     *
     * @mbggenerated
     */
    public void setClientSecrect(String clientSecrect) {
        this.clientSecrect = clientSecrect == null ? null : clientSecrect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_unit_account.is_lock
     *
     * @return the value of open_unit_account.is_lock
     *
     * @mbggenerated
     */
    public Byte getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_unit_account.is_lock
     *
     * @param isLock the value for open_unit_account.is_lock
     *
     * @mbggenerated
     */
    public void setIsLock(Byte isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_unit_account.white_ip
     *
     * @return the value of open_unit_account.white_ip
     *
     * @mbggenerated
     */
    public String getWhiteIp() {
        return whiteIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_unit_account.white_ip
     *
     * @param whiteIp the value for open_unit_account.white_ip
     *
     * @mbggenerated
     */
    public void setWhiteIp(String whiteIp) {
        this.whiteIp = whiteIp == null ? null : whiteIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_unit_account.max_per_minute
     *
     * @return the value of open_unit_account.max_per_minute
     *
     * @mbggenerated
     */
    public Integer getMaxPerMinute() {
        return maxPerMinute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_unit_account.max_per_minute
     *
     * @param maxPerMinute the value for open_unit_account.max_per_minute
     *
     * @mbggenerated
     */
    public void setMaxPerMinute(Integer maxPerMinute) {
        this.maxPerMinute = maxPerMinute;
    }

    /**
     * Getter method for property <tt>remark</tt>.
     * 
     * @return property value of remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Setter method for property <tt>remark</tt>.
     * 
     * @param remark value to be assigned to property remark
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_unit_account.gmt_create
     *
     * @return the value of open_unit_account.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_unit_account.gmt_create
     *
     * @param gmtCreate the value for open_unit_account.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column open_unit_account.gmt_modified
     *
     * @return the value of open_unit_account.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column open_unit_account.gmt_modified
     *
     * @param gmtModified the value for open_unit_account.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getManagerPass() {
        return managerPass;
    }

    public void setManagerPass(String managerPass) {
        this.managerPass = managerPass;
    }
}