package com.efida.sports.dmp.dao.entity;

import java.util.Date;

public class ReportGoodsOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_goods_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_goods_order.date
     *
     * @mbggenerated
     */
    private Date    date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_goods_order.finish_count
     *
     * @mbggenerated
     */
    private Integer finishCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_goods_order.medal_receive
     *
     * @mbggenerated
     */
    private Integer medalReceive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_goods_order.entity_receive
     *
     * @mbggenerated
     */
    private Integer entityReceive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_goods_order.online_order
     *
     * @mbggenerated
     */
    private Integer onlineOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_goods_order.gmt_create
     *
     * @mbggenerated
     */
    private Date    gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report_goods_order.gmt_modified
     *
     * @mbggenerated
     */
    private Date    gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_goods_order.id
     *
     * @return the value of report_goods_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_goods_order.id
     *
     * @param id the value for report_goods_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_goods_order.date
     *
     * @return the value of report_goods_order.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_goods_order.date
     *
     * @param date the value for report_goods_order.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_goods_order.finish_count
     *
     * @return the value of report_goods_order.finish_count
     *
     * @mbggenerated
     */
    public Integer getFinishCount() {
        return finishCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_goods_order.finish_count
     *
     * @param finishCount the value for report_goods_order.finish_count
     *
     * @mbggenerated
     */
    public void setFinishCount(Integer finishCount) {
        this.finishCount = finishCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_goods_order.medal_receive
     *
     * @return the value of report_goods_order.medal_receive
     *
     * @mbggenerated
     */
    public Integer getMedalReceive() {
        return medalReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_goods_order.medal_receive
     *
     * @param medalReceive the value for report_goods_order.medal_receive
     *
     * @mbggenerated
     */
    public void setMedalReceive(Integer medalReceive) {
        this.medalReceive = medalReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_goods_order.entity_receive
     *
     * @return the value of report_goods_order.entity_receive
     *
     * @mbggenerated
     */
    public Integer getEntityReceive() {
        return entityReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_goods_order.entity_receive
     *
     * @param entityReceive the value for report_goods_order.entity_receive
     *
     * @mbggenerated
     */
    public void setEntityReceive(Integer entityReceive) {
        this.entityReceive = entityReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_goods_order.online_order
     *
     * @return the value of report_goods_order.online_order
     *
     * @mbggenerated
     */
    public Integer getOnlineOrder() {
        return onlineOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_goods_order.online_order
     *
     * @param onlineOrder the value for report_goods_order.online_order
     *
     * @mbggenerated
     */
    public void setOnlineOrder(Integer onlineOrder) {
        this.onlineOrder = onlineOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_goods_order.gmt_create
     *
     * @return the value of report_goods_order.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_goods_order.gmt_create
     *
     * @param gmtCreate the value for report_goods_order.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report_goods_order.gmt_modified
     *
     * @return the value of report_goods_order.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report_goods_order.gmt_modified
     *
     * @param gmtModified the value for report_goods_order.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}