package com.efida.sports.dmp.dao.entity;

import java.util.Date;

public class ScoreCertMaxNoEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_maxno.id
     *
     * @mbggenerated
     */
    private Long    id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_maxno.cert_year
     *
     * @mbggenerated
     */
    private String  certYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_maxno.current_no
     *
     * @mbggenerated
     */
    private Integer currentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_maxno.gmt_create
     *
     * @mbggenerated
     */
    private Date    gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_maxno.gmt_modified
     *
     * @mbggenerated
     */
    private Date    gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_maxno.id
     *
     * @return the value of score_cert_maxno.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_maxno.id
     *
     * @param id the value for score_cert_maxno.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_maxno.cert_year
     *
     * @return the value of score_cert_maxno.cert_year
     *
     * @mbggenerated
     */
    public String getCertYear() {
        return certYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_maxno.cert_year
     *
     * @param certYear the value for score_cert_maxno.cert_year
     *
     * @mbggenerated
     */
    public void setCertYear(String certYear) {
        this.certYear = certYear == null ? null : certYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_maxno.current_no
     *
     * @return the value of score_cert_maxno.current_no
     *
     * @mbggenerated
     */
    public Integer getCurrentNo() {
        return currentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_maxno.current_no
     *
     * @param currentNo the value for score_cert_maxno.current_no
     *
     * @mbggenerated
     */
    public void setCurrentNo(Integer currentNo) {
        this.currentNo = currentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_maxno.gmt_create
     *
     * @return the value of score_cert_maxno.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_maxno.gmt_create
     *
     * @param gmtCreate the value for score_cert_maxno.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_maxno.gmt_modified
     *
     * @return the value of score_cert_maxno.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_maxno.gmt_modified
     *
     * @param gmtModified the value for score_cert_maxno.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}