package com.efida.sports.dmp.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

import cn.evake.auth.util.DateUtil;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "成绩证书模型")
public class ScoreCertEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.id
     *
     * @mbggenerated
     */
    private Long       id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.cert_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "证书内部编号")
    private String     certCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.register_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "账号ID")
    private String     registerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.player_phone
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "运动员电话")
    private String     playerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.cert_sn
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "证书序列号")
    private String     certSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.cert_no
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "证书当年编号")
    private Integer    certNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.cert_year
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "证书年份")
    private String     certYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.cert_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "证书颁发时间")
    private Date       certTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.cert_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "证书颁发姓名")
    private String     certName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.cert_match_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "证书上赛事名")
    private String     certMatchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.cert_event_name
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "证书上比赛描述")
    private String     certEventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.cert_pic_url
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "  证书图片")
    private String     certPicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.cert_short_pic_url
     *
     * @mbggenerated
     */
    private String     certShortPicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.pic_code
     *
     * @mbggenerated
     */
    private String     picCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.generate_pic_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "  证书图片产生时间")
    private Date       generatePicTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.is_view_pic
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "  是否已经查看证书")
    private Boolean    isViewPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.is_pic_ok
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "  证书图片是否正常")
    private Boolean    isPicOk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.need_generate_pic
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "  是否需要生成证书图片")
    private Boolean    needGeneratePic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.nex_pic_time
     *
     * @mbggenerated
     */
    private Date       nexPicTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.generate_pic_total
     *
     * @mbggenerated
     */
    private Integer    generatePicTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.pic_status
     *
     * @mbggenerated
     */
    private String     picStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.is_sms_send
     *
     * @mbggenerated
     */

    @ApiModelProperty(value = "  是否已经发短信")
    private Boolean    isSmsSend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.sms_send_time
     *
     * @mbggenerated
     */
    private Date       smsSendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.need_send_sms
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "是否需要发送短信")
    private Boolean    needSendSms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.next_send_sms_time
     *
     * @mbggenerated
     */
    private Date       nextSendSmsTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.send_sms_total
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "短信发送次数")
    private Integer    sendSmsTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.sms_status
     *
     * @mbggenerated
     */
    private String     smsStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.score_rank_code
     *
     * @mbggenerated
     */
    private String     scoreRankCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.player_code
     *
     * @mbggenerated
     */
    private String     playerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.player_name
     *
     * @mbggenerated
     */
    private String     playerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.part_time
     *
     * @mbggenerated
     */
    private Date       partTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.match_code
     *
     * @mbggenerated
     */
    private String     matchCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.match_name
     *
     * @mbggenerated
     */
    private String     matchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.field_code
     *
     * @mbggenerated
     */
    private String     fieldCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.field_name
     *
     * @mbggenerated
     */
    private String     fieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.match_group_code
     *
     * @mbggenerated
     */
    private String     matchGroupCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.match_group_name
     *
     * @mbggenerated
     */
    private String     matchGroupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.event_code
     *
     * @mbggenerated
     */
    private String     eventCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.event_name
     *
     * @mbggenerated
     */
    private String     eventName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.score_name
     *
     * @mbggenerated
     */
    private String     scoreName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.score
     *
     * @mbggenerated
     */
    private BigDecimal score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.score_unit
     *
     * @mbggenerated
     */
    private String     scoreUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.score_desc
     *
     * @mbggenerated
     */
    private String     scoreDesc;
    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column open_score_rank.ranking
    *
    * @mbggenerated
    */
    private Integer    ranking;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.channel_code
     *
     * @mbggenerated
     */
    private String     channelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.unit_code
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "承办方编号")
    private String     unitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.idempotent_id
     *
     * @mbggenerated
     */
    private String     idempotentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.is_valid
     *
     * @mbggenerated
     */
    private Boolean    isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.status
     *
     * @mbggenerated
     */
    private String     status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.status_desc
     *
     * @mbggenerated
     */
    private String     statusDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.gmt_create
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "创建时间")
    private Date       gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert.gmt_modified
     *
     * @mbggenerated
     */
    private Date       gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.id
     *
     * @return the value of score_cert.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.id
     *
     * @param id the value for score_cert.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.cert_code
     *
     * @return the value of score_cert.cert_code
     *
     * @mbggenerated
     */
    public String getCertCode() {
        return certCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.cert_code
     *
     * @param certCode the value for score_cert.cert_code
     *
     * @mbggenerated
     */
    public void setCertCode(String certCode) {
        this.certCode = certCode == null ? null : certCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.register_code
     *
     * @return the value of score_cert.register_code
     *
     * @mbggenerated
     */
    public String getRegisterCode() {
        return registerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.register_code
     *
     * @param registerCode the value for score_cert.register_code
     *
     * @mbggenerated
     */
    public void setRegisterCode(String registerCode) {
        this.registerCode = registerCode == null ? null : registerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.player_phone
     *
     * @return the value of score_cert.player_phone
     *
     * @mbggenerated
     */
    public String getPlayerPhone() {
        return playerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.player_phone
     *
     * @param playerPhone the value for score_cert.player_phone
     *
     * @mbggenerated
     */
    public void setPlayerPhone(String playerPhone) {
        this.playerPhone = playerPhone == null ? null : playerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.cert_sn
     *
     * @return the value of score_cert.cert_sn
     *
     * @mbggenerated
     */
    public String getCertSn() {
        return certSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.cert_sn
     *
     * @param certSn the value for score_cert.cert_sn
     *
     * @mbggenerated
     */
    public void setCertSn(String certSn) {
        this.certSn = certSn == null ? null : certSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.cert_no
     *
     * @return the value of score_cert.cert_no
     *
     * @mbggenerated
     */
    public Integer getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.cert_no
     *
     * @param certNo the value for score_cert.cert_no
     *
     * @mbggenerated
     */
    public void setCertNo(Integer certNo) {
        this.certNo = certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.cert_year
     *
     * @return the value of score_cert.cert_year
     *
     * @mbggenerated
     */
    public String getCertYear() {
        return certYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.cert_year
     *
     * @param certYear the value for score_cert.cert_year
     *
     * @mbggenerated
     */
    public void setCertYear(String certYear) {
        this.certYear = certYear == null ? null : certYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.cert_time
     *
     * @return the value of score_cert.cert_time
     *
     * @mbggenerated
     */
    public Date getCertTime() {
        return certTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.cert_time
     *
     * @param certTime the value for score_cert.cert_time
     *
     * @mbggenerated
     */
    public void setCertTime(Date certTime) {
        this.certTime = certTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.cert_name
     *
     * @return the value of score_cert.cert_name
     *
     * @mbggenerated
     */
    public String getCertName() {
        return certName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.cert_name
     *
     * @param certName the value for score_cert.cert_name
     *
     * @mbggenerated
     */
    public void setCertName(String certName) {
        this.certName = certName == null ? null : certName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.cert_match_name
     *
     * @return the value of score_cert.cert_match_name
     *
     * @mbggenerated
     */
    public String getCertMatchName() {
        return certMatchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.cert_match_name
     *
     * @param certMatchName the value for score_cert.cert_match_name
     *
     * @mbggenerated
     */
    public void setCertMatchName(String certMatchName) {
        this.certMatchName = certMatchName == null ? null : certMatchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.cert_event_name
     *
     * @return the value of score_cert.cert_event_name
     *
     * @mbggenerated
     */
    public String getCertEventName() {
        return certEventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.cert_event_name
     *
     * @param certEventName the value for score_cert.cert_event_name
     *
     * @mbggenerated
     */
    public void setCertEventName(String certEventName) {
        this.certEventName = certEventName == null ? null : certEventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.cert_pic_url
     *
     * @return the value of score_cert.cert_pic_url
     *
     * @mbggenerated
     */
    public String getCertPicUrl() {
        return certPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.cert_pic_url
     *
     * @param certPicUrl the value for score_cert.cert_pic_url
     *
     * @mbggenerated
     */
    public void setCertPicUrl(String certPicUrl) {
        this.certPicUrl = certPicUrl == null ? null : certPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.cert_short_pic_url
     *
     * @return the value of score_cert.cert_short_pic_url
     *
     * @mbggenerated
     */
    public String getCertShortPicUrl() {
        return certShortPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.cert_short_pic_url
     *
     * @param certShortPicUrl the value for score_cert.cert_short_pic_url
     *
     * @mbggenerated
     */
    public void setCertShortPicUrl(String certShortPicUrl) {
        this.certShortPicUrl = certShortPicUrl == null ? null : certShortPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.pic_code
     *
     * @return the value of score_cert.pic_code
     *
     * @mbggenerated
     */
    public String getPicCode() {
        return picCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.pic_code
     *
     * @param picCode the value for score_cert.pic_code
     *
     * @mbggenerated
     */
    public void setPicCode(String picCode) {
        this.picCode = picCode == null ? null : picCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.generate_pic_time
     *
     * @return the value of score_cert.generate_pic_time
     *
     * @mbggenerated
     */
    public Date getGeneratePicTime() {
        return generatePicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.generate_pic_time
     *
     * @param generatePicTime the value for score_cert.generate_pic_time
     *
     * @mbggenerated
     */
    public void setGeneratePicTime(Date generatePicTime) {
        this.generatePicTime = generatePicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.is_view_pic
     *
     * @return the value of score_cert.is_view_pic
     *
     * @mbggenerated
     */
    public Boolean getIsViewPic() {
        return isViewPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.is_view_pic
     *
     * @param isViewPic the value for score_cert.is_view_pic
     *
     * @mbggenerated
     */
    public void setIsViewPic(Boolean isViewPic) {
        this.isViewPic = isViewPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.is_pic_ok
     *
     * @return the value of score_cert.is_pic_ok
     *
     * @mbggenerated
     */
    public Boolean getIsPicOk() {
        return isPicOk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.is_pic_ok
     *
     * @param isPicOk the value for score_cert.is_pic_ok
     *
     * @mbggenerated
     */
    public void setIsPicOk(Boolean isPicOk) {
        this.isPicOk = isPicOk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.need_generate_pic
     *
     * @return the value of score_cert.need_generate_pic
     *
     * @mbggenerated
     */
    public Boolean getNeedGeneratePic() {
        return needGeneratePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.need_generate_pic
     *
     * @param needGeneratePic the value for score_cert.need_generate_pic
     *
     * @mbggenerated
     */
    public void setNeedGeneratePic(Boolean needGeneratePic) {
        this.needGeneratePic = needGeneratePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.nex_pic_time
     *
     * @return the value of score_cert.nex_pic_time
     *
     * @mbggenerated
     */
    public Date getNexPicTime() {
        return nexPicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.nex_pic_time
     *
     * @param nexPicTime the value for score_cert.nex_pic_time
     *
     * @mbggenerated
     */
    public void setNexPicTime(Date nexPicTime) {
        this.nexPicTime = nexPicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.generate_pic_total
     *
     * @return the value of score_cert.generate_pic_total
     *
     * @mbggenerated
     */
    public Integer getGeneratePicTotal() {
        return generatePicTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.generate_pic_total
     *
     * @param generatePicTotal the value for score_cert.generate_pic_total
     *
     * @mbggenerated
     */
    public void setGeneratePicTotal(Integer generatePicTotal) {
        this.generatePicTotal = generatePicTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.pic_status
     *
     * @return the value of score_cert.pic_status
     *
     * @mbggenerated
     */
    public String getPicStatus() {
        return picStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.pic_status
     *
     * @param picStatus the value for score_cert.pic_status
     *
     * @mbggenerated
     */
    public void setPicStatus(String picStatus) {
        this.picStatus = picStatus == null ? null : picStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.is_sms_send
     *
     * @return the value of score_cert.is_sms_send
     *
     * @mbggenerated
     */
    public Boolean getIsSmsSend() {
        return isSmsSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.is_sms_send
     *
     * @param isSmsSend the value for score_cert.is_sms_send
     *
     * @mbggenerated
     */
    public void setIsSmsSend(Boolean isSmsSend) {
        this.isSmsSend = isSmsSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.sms_send_time
     *
     * @return the value of score_cert.sms_send_time
     *
     * @mbggenerated
     */
    public Date getSmsSendTime() {
        return smsSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.sms_send_time
     *
     * @param smsSendTime the value for score_cert.sms_send_time
     *
     * @mbggenerated
     */
    public void setSmsSendTime(Date smsSendTime) {
        this.smsSendTime = smsSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.need_send_sms
     *
     * @return the value of score_cert.need_send_sms
     *
     * @mbggenerated
     */
    public Boolean getNeedSendSms() {
        return needSendSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.need_send_sms
     *
     * @param needSendSms the value for score_cert.need_send_sms
     *
     * @mbggenerated
     */
    public void setNeedSendSms(Boolean needSendSms) {
        this.needSendSms = needSendSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.next_send_sms_time
     *
     * @return the value of score_cert.next_send_sms_time
     *
     * @mbggenerated
     */
    public Date getNextSendSmsTime() {
        return nextSendSmsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.next_send_sms_time
     *
     * @param nextSendSmsTime the value for score_cert.next_send_sms_time
     *
     * @mbggenerated
     */
    public void setNextSendSmsTime(Date nextSendSmsTime) {
        this.nextSendSmsTime = nextSendSmsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.send_sms_total
     *
     * @return the value of score_cert.send_sms_total
     *
     * @mbggenerated
     */
    public Integer getSendSmsTotal() {
        return sendSmsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.send_sms_total
     *
     * @param sendSmsTotal the value for score_cert.send_sms_total
     *
     * @mbggenerated
     */
    public void setSendSmsTotal(Integer sendSmsTotal) {
        this.sendSmsTotal = sendSmsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.sms_status
     *
     * @return the value of score_cert.sms_status
     *
     * @mbggenerated
     */
    public String getSmsStatus() {
        return smsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.sms_status
     *
     * @param smsStatus the value for score_cert.sms_status
     *
     * @mbggenerated
     */
    public void setSmsStatus(String smsStatus) {
        this.smsStatus = smsStatus == null ? null : smsStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.score_rank_code
     *
     * @return the value of score_cert.score_rank_code
     *
     * @mbggenerated
     */
    public String getScoreRankCode() {
        return scoreRankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.score_rank_code
     *
     * @param scoreRankCode the value for score_cert.score_rank_code
     *
     * @mbggenerated
     */
    public void setScoreRankCode(String scoreRankCode) {
        this.scoreRankCode = scoreRankCode == null ? null : scoreRankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.player_code
     *
     * @return the value of score_cert.player_code
     *
     * @mbggenerated
     */
    public String getPlayerCode() {
        return playerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.player_code
     *
     * @param playerCode the value for score_cert.player_code
     *
     * @mbggenerated
     */
    public void setPlayerCode(String playerCode) {
        this.playerCode = playerCode == null ? null : playerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.player_name
     *
     * @return the value of score_cert.player_name
     *
     * @mbggenerated
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.player_name
     *
     * @param playerName the value for score_cert.player_name
     *
     * @mbggenerated
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName == null ? null : playerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.part_time
     *
     * @return the value of score_cert.part_time
     *
     * @mbggenerated
     */
    public Date getPartTime() {
        return partTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.part_time
     *
     * @param partTime the value for score_cert.part_time
     *
     * @mbggenerated
     */
    public void setPartTime(Date partTime) {
        this.partTime = partTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.match_code
     *
     * @return the value of score_cert.match_code
     *
     * @mbggenerated
     */
    public String getMatchCode() {
        return matchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.match_code
     *
     * @param matchCode the value for score_cert.match_code
     *
     * @mbggenerated
     */
    public void setMatchCode(String matchCode) {
        this.matchCode = matchCode == null ? null : matchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.match_name
     *
     * @return the value of score_cert.match_name
     *
     * @mbggenerated
     */
    public String getMatchName() {
        return matchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.match_name
     *
     * @param matchName the value for score_cert.match_name
     *
     * @mbggenerated
     */
    public void setMatchName(String matchName) {
        this.matchName = matchName == null ? null : matchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.field_code
     *
     * @return the value of score_cert.field_code
     *
     * @mbggenerated
     */
    public String getFieldCode() {
        return fieldCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.field_code
     *
     * @param fieldCode the value for score_cert.field_code
     *
     * @mbggenerated
     */
    public void setFieldCode(String fieldCode) {
        this.fieldCode = fieldCode == null ? null : fieldCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.field_name
     *
     * @return the value of score_cert.field_name
     *
     * @mbggenerated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.field_name
     *
     * @param fieldName the value for score_cert.field_name
     *
     * @mbggenerated
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.match_group_code
     *
     * @return the value of score_cert.match_group_code
     *
     * @mbggenerated
     */
    public String getMatchGroupCode() {
        return matchGroupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.match_group_code
     *
     * @param matchGroupCode the value for score_cert.match_group_code
     *
     * @mbggenerated
     */
    public void setMatchGroupCode(String matchGroupCode) {
        this.matchGroupCode = matchGroupCode == null ? null : matchGroupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.match_group_name
     *
     * @return the value of score_cert.match_group_name
     *
     * @mbggenerated
     */
    public String getMatchGroupName() {
        return matchGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.match_group_name
     *
     * @param matchGroupName the value for score_cert.match_group_name
     *
     * @mbggenerated
     */
    public void setMatchGroupName(String matchGroupName) {
        this.matchGroupName = matchGroupName == null ? null : matchGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.event_code
     *
     * @return the value of score_cert.event_code
     *
     * @mbggenerated
     */
    public String getEventCode() {
        return eventCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.event_code
     *
     * @param eventCode the value for score_cert.event_code
     *
     * @mbggenerated
     */
    public void setEventCode(String eventCode) {
        this.eventCode = eventCode == null ? null : eventCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.event_name
     *
     * @return the value of score_cert.event_name
     *
     * @mbggenerated
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.event_name
     *
     * @param eventName the value for score_cert.event_name
     *
     * @mbggenerated
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.score_name
     *
     * @return the value of score_cert.score_name
     *
     * @mbggenerated
     */
    public String getScoreName() {
        return scoreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.score_name
     *
     * @param scoreName the value for score_cert.score_name
     *
     * @mbggenerated
     */
    public void setScoreName(String scoreName) {
        this.scoreName = scoreName == null ? null : scoreName.trim();
    }

    public BigDecimal getScore() {
        return score;
    }

    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.score_unit
     *
     * @return the value of score_cert.score_unit
     *
     * @mbggenerated
     */
    public String getScoreUnit() {
        return scoreUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.score_unit
     *
     * @param scoreUnit the value for score_cert.score_unit
     *
     * @mbggenerated
     */
    public void setScoreUnit(String scoreUnit) {
        this.scoreUnit = scoreUnit == null ? null : scoreUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.score_desc
     *
     * @return the value of score_cert.score_desc
     *
     * @mbggenerated
     */
    public String getScoreDesc() {
        return scoreDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.score_desc
     *
     * @param scoreDesc the value for score_cert.score_desc
     *
     * @mbggenerated
     */
    public void setScoreDesc(String scoreDesc) {
        this.scoreDesc = scoreDesc == null ? null : scoreDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.channel_code
     *
     * @return the value of score_cert.channel_code
     *
     * @mbggenerated
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.channel_code
     *
     * @param channelCode the value for score_cert.channel_code
     *
     * @mbggenerated
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.unit_code
     *
     * @return the value of score_cert.unit_code
     *
     * @mbggenerated
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.unit_code
     *
     * @param unitCode the value for score_cert.unit_code
     *
     * @mbggenerated
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode == null ? null : unitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.idempotent_id
     *
     * @return the value of score_cert.idempotent_id
     *
     * @mbggenerated
     */
    public String getIdempotentId() {
        return idempotentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.idempotent_id
     *
     * @param idempotentId the value for score_cert.idempotent_id
     *
     * @mbggenerated
     */
    public void setIdempotentId(String idempotentId) {
        this.idempotentId = idempotentId == null ? null : idempotentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.is_valid
     *
     * @return the value of score_cert.is_valid
     *
     * @mbggenerated
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.is_valid
     *
     * @param isValid the value for score_cert.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.status
     *
     * @return the value of score_cert.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.status
     *
     * @param status the value for score_cert.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.status_desc
     *
     * @return the value of score_cert.status_desc
     *
     * @mbggenerated
     */
    public String getStatusDesc() {
        return statusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.status_desc
     *
     * @param statusDesc the value for score_cert.status_desc
     *
     * @mbggenerated
     */
    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc == null ? null : statusDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.gmt_create
     *
     * @return the value of score_cert.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.gmt_create
     *
     * @param gmtCreate the value for score_cert.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert.gmt_modified
     *
     * @return the value of score_cert.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    public String getGmtCreateStr() {
        return gmtCreate == null ? null : DateUtil.formatDate(gmtCreate);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert.gmt_modified
     *
     * @param gmtModified the value for score_cert.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public Integer getRanking() {
        return ranking;
    }

    public void setRanking(Integer ranking) {
        this.ranking = ranking;
    }
}