package com.efida.sports.dmp.dao.entity;

import java.util.Date;

public class ScoreCertNoEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_no.id
     *
     * @mbggenerated
     */
    private Long    id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_no.cert_year
     *
     * @mbggenerated
     */
    private String  certYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_no.cert_no
     *
     * @mbggenerated
     */
    private Integer certNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_no.cert_sn
     *
     * @mbggenerated
     */
    private String  certSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_no.is_use
     *
     * @mbggenerated
     */
    private Boolean isUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_no.assignment_time
     *
     * @mbggenerated
     */
    private Date    assignmentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_no.cert_code
     *
     * @mbggenerated
     */
    private String  certCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_no.regiser_code
     *
     * @mbggenerated
     */
    private String  regiserCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_no.gmt_create
     *
     * @mbggenerated
     */
    private Date    gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_no.gmt_modified
     *
     * @mbggenerated
     */
    private Date    gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_no.id
     *
     * @return the value of score_cert_no.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_no.id
     *
     * @param id the value for score_cert_no.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_no.cert_year
     *
     * @return the value of score_cert_no.cert_year
     *
     * @mbggenerated
     */
    public String getCertYear() {
        return certYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_no.cert_year
     *
     * @param certYear the value for score_cert_no.cert_year
     *
     * @mbggenerated
     */
    public void setCertYear(String certYear) {
        this.certYear = certYear == null ? null : certYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_no.cert_no
     *
     * @return the value of score_cert_no.cert_no
     *
     * @mbggenerated
     */
    public Integer getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_no.cert_no
     *
     * @param certNo the value for score_cert_no.cert_no
     *
     * @mbggenerated
     */
    public void setCertNo(Integer certNo) {
        this.certNo = certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_no.cert_sn
     *
     * @return the value of score_cert_no.cert_sn
     *
     * @mbggenerated
     */
    public String getCertSn() {
        return certSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_no.cert_sn
     *
     * @param certSn the value for score_cert_no.cert_sn
     *
     * @mbggenerated
     */
    public void setCertSn(String certSn) {
        this.certSn = certSn == null ? null : certSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_no.is_use
     *
     * @return the value of score_cert_no.is_use
     *
     * @mbggenerated
     */
    public Boolean getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_no.is_use
     *
     * @param isUse the value for score_cert_no.is_use
     *
     * @mbggenerated
     */
    public void setIsUse(Boolean isUse) {
        this.isUse = isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_no.assignment_time
     *
     * @return the value of score_cert_no.assignment_time
     *
     * @mbggenerated
     */
    public Date getAssignmentTime() {
        return assignmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_no.assignment_time
     *
     * @param assignmentTime the value for score_cert_no.assignment_time
     *
     * @mbggenerated
     */
    public void setAssignmentTime(Date assignmentTime) {
        this.assignmentTime = assignmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_no.cert_code
     *
     * @return the value of score_cert_no.cert_code
     *
     * @mbggenerated
     */
    public String getCertCode() {
        return certCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_no.cert_code
     *
     * @param certCode the value for score_cert_no.cert_code
     *
     * @mbggenerated
     */
    public void setCertCode(String certCode) {
        this.certCode = certCode == null ? null : certCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_no.regiser_code
     *
     * @return the value of score_cert_no.regiser_code
     *
     * @mbggenerated
     */
    public String getRegiserCode() {
        return regiserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_no.regiser_code
     *
     * @param regiserCode the value for score_cert_no.regiser_code
     *
     * @mbggenerated
     */
    public void setRegiserCode(String regiserCode) {
        this.regiserCode = regiserCode == null ? null : regiserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_no.gmt_create
     *
     * @return the value of score_cert_no.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_no.gmt_create
     *
     * @param gmtCreate the value for score_cert_no.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_no.gmt_modified
     *
     * @return the value of score_cert_no.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_no.gmt_modified
     *
     * @param gmtModified the value for score_cert_no.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}