# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：  
#   测试环境：java -jar xxx.jar --server.port=18080 --spring.profiles.active=test  
#   生产环境：java -jar xxx.jar --server.port=18080 --spring.profiles.active=prod
# dev  config
spring:
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB  
  profiles:  
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.115.40.84:23306/sports?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: sports
    password: VbuQLFCyyr1VMs8
    initialize: true
    initial-size: 20
    max-active: 100
  redis:  
    pool:
      max-idle: 1000    
      min-idle: 200    
      max-active: 10000
      max-wait: 10000
    host: 127.0.01
    port: 6379
  freemarker: 
    allow-request-override: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefer-file-system-access: false
    suffix: .html
  dubbo:
      protocol:
        name: dubbo
      application:
        name: sports
        owner: zoutao
      registry:
        address: zookeeper://127.0.0.1
        port: 2181
      base-package: com.efida.sports.service.dubbo
      consumer:
        timeout: 20000 
        check: false                        # 服务启动时检查被调用服务是否可用
        retries: 2  

mybatis-plus: 
  mapper-locations: classpath*:com/efida/sports/mapper/*.xml
  type-aliases-package: com.efida.sports.entity
  
runSycTask : false

server:  
  port: 9998
  tomcat:
    max-threads: 2000
ALiPay:
  partner: 2088031073324450
  notifyUrl: http://devappapi.zntyydh.com/order/alipay/pay/callback
  returnUrl: http://devappapi.zntyydh.com/order/alipay/gateway/
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxWMHag4uwCHMneanvb4ZtawTRimEnbIWp6cFoQNf2bGxImScLfXzsolVy3Jw908ANbEJAFPAxTHfQDkeF6HEL5ylRW7DRDgsXjqgtH3QhuDNTZ8f9djNHN3d1Pp2QOgYxytnwpmt0+HEF2r0OsI+5MEtyYU5BD7a/4hOGGq59atnAeegqtzpMRzBuXnR4IdC+juuLCiUp+KeKyV5DYyOmm/BragEBAMtRWAW/IHaWwS0pxgFqahB15iXgWkKVgLqltHsPGTTE15v02TPhddoBshdA6GIDku7meBw7eqqbvUFwlE1W6k/obeJv9LocKIGGzwJ2S6haQvWBfDlm90b7QIDAQAB
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDFYwdqDi7AIcyd5qe9vhm1rBNGKYSdshanpwWhA1/ZsbEiZJwt9fOyiVXLcnD3TwA1sQkAU8DFMd9AOR4XocQvnKVFbsNEOCxeOqC0fdCG4M1Nnx/12M0c3d3U+nZA6BjHK2fCma3T4cQXavQ6wj7kwS3JhTkEPtr/iE4Yarn1q2cB56Cq3OkxHMG5edHgh0L6O64sKJSn4p4rJXkNjI6ab8GtqAQEAy1FYBb8gdpbBLSnGAWpqEHXmJeBaQpWAuqW0ew8ZNMTXm/TZM+F12gGyF0DoYgOS7uZ4HDt6qpu9QXCUTVbqT+ht4m/0uhwogYbPAnZLqFpC9YF8OWb3RvtAgMBAAECggEAVxWTxdSwB5Bh6CBFTU87pI1gi4nxumlB2YG02A7XEQJ2dggRZ62lcNVqhrHc6R9vpkCPChfpapbQOlN41VBHcAIaYIG3oLdvy7rt//OqNnej3GUiAqM+C0hPgJFn7sb3d5fM1Wxb5qkqjHJhgjME8IPSIaCnQRpCII8QdXFQzfOkOebvLvvYKNTx8Ndy0cb7EuWhArDqqrszUPyDWW+D7mgz+5YDMWie8lwkMLkQRZ5kgeAIWN9K0mVTSkoauc7cC1ICQ2/l68+Mrc8fznKmkoqpm1TxUZ8VloQEttR61z8CElueXLg7fBb9f4rlFwJ9QGqbP3x5lbr9iDKMoytiAQKBgQDyZjiqvEjmDYJ8EORl3fGAGMTRmT3anmrJM37/NJ8iPiDXO28OnsemgbvonfRz6BDljUZh8xoXF4lZEJKw0SnPXOgFYPt6eLd881Isijq0mV4Wyu733l5vE/vFep5m08f1321R/6WJ7FPm9tyxdmaKtqnxecGlYJDzU5y+cyvgLQKBgQDQdkG/bazB6mor0y0S0sapj0/n0MC2STwRa3XG4FJTyHKqBwm1I64prxc9pLeAEOYnvj9oUELgaoe2Si/RT+xotqVpgmA28cLMcAUzLinbhlYsvXuKKV8c+z7cnfsGLj1b8kfpluw1u3VvjU0VQ0xIxrnDbZyt9Ueg2VIAwOPCwQKBgHHIL/Nc/G8YilaIa12xx8nUVpb4csNrNz8IsCVFYylktm+xk1juiVMMdNMlSfkaRswp+47A2U9bmfo3wFPFavXOa48SzhjYD3FUmg8UN6hMkZDrYy7wr60+WSGChFZKNQOiBCPId8D9MQkqeb/Hjyyvv6f8+jwRzxiY9+uiDkdlAoGAMIlIN6T2k1PcEoYhuX8/6BzJEwVkyUx14uxtSLfUE1PZdsMavIUpOOVeeOjQHM5SeDBwnP4LBCtpm8TcK1T7i0nza4SCmGhj3au7WjZGYql9iP85M2r8jUfmVAGof8DmYnEf00BjkQMrjaSNrQS1T0CN4fW0hEBWxBm1YR2IKkECgYEAo4D6iyaVkObA0sU+xOG+Ugz57jv3Uh4gTxzuPsfB9+sc9jHTkA87qU3cHQDj0JVfBgavYmPAp5k1f6H8XICxQHTr3vCy4WmMb0zwp98dtK+NMahI2pk/uPukOaqmYXT1zGMT0ZsteSSh/2PJKA9GMabmq3QIlRePEZ1a0Md4WgY=
  appId: 2018062660422282


weichat:
  appId: wx7570f2e03d6d90f5
  redirectUri: http://devappapi.zntyydh.com/auth/weixin/authcallback
  appSecret: 24bdc86540878d88dd9c20af87bb4744
  pay:
    mchId: 1508180271 
    apiKey: 3n1iMXSvlqVSAbpyCKqOtbRBJFZbvebb
    unifiedorder: https://api.mch.weixin.qq.com/pay/unifiedorder
    notifyUrl: http://devappapi.zntyydh.com/order/weichat/notify
sms:
  uid: 211591
  pwd: e85619909747b13f8a53b90fb6655d07 
  
  
---
# 测试环境
spring:
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB   
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.zntyydh.com:3306/sports?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: sports
    password: DevVbuQLFCyyr1VMs8
    initialize: true
    initial-size: 20
    max-active: 100
  redis:  
    pool:
      max-idle: 50    
      min-idle: 10    
      max-active: 5000
      max-wait: 10000
    host: redis.zntyydh.com
    port: 7000
    password: DevZNTY5lqUdYE7oA6C18
  freemarker: 
    allow-request-override: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefer-file-system-access: false
    suffix: .html
  dubbo:
      protocol:
        name: dubbo
      application:
        name: sports
        owner: zoutao
      registry:
        address: zookeeper://zookeeper.zntyydh.com:9075
        port: 21804
      base-package: com.efida.sports.service.dubbo
      consumer:
        timeout: 20000 
        check: false                        # 服务启动时检查被调用服务是否可用
        retries: 2
 
ALiPay:
  partner: 2088031073324450
  notifyUrl: http://devappapi.zntyydh.com/order/alipay/pay/callback
  returnUrl: http://devappapi.zntyydh.com/order/alipay/gateway/
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxWMHag4uwCHMneanvb4ZtawTRimEnbIWp6cFoQNf2bGxImScLfXzsolVy3Jw908ANbEJAFPAxTHfQDkeF6HEL5ylRW7DRDgsXjqgtH3QhuDNTZ8f9djNHN3d1Pp2QOgYxytnwpmt0+HEF2r0OsI+5MEtyYU5BD7a/4hOGGq59atnAeegqtzpMRzBuXnR4IdC+juuLCiUp+KeKyV5DYyOmm/BragEBAMtRWAW/IHaWwS0pxgFqahB15iXgWkKVgLqltHsPGTTE15v02TPhddoBshdA6GIDku7meBw7eqqbvUFwlE1W6k/obeJv9LocKIGGzwJ2S6haQvWBfDlm90b7QIDAQAB
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDFYwdqDi7AIcyd5qe9vhm1rBNGKYSdshanpwWhA1/ZsbEiZJwt9fOyiVXLcnD3TwA1sQkAU8DFMd9AOR4XocQvnKVFbsNEOCxeOqC0fdCG4M1Nnx/12M0c3d3U+nZA6BjHK2fCma3T4cQXavQ6wj7kwS3JhTkEPtr/iE4Yarn1q2cB56Cq3OkxHMG5edHgh0L6O64sKJSn4p4rJXkNjI6ab8GtqAQEAy1FYBb8gdpbBLSnGAWpqEHXmJeBaQpWAuqW0ew8ZNMTXm/TZM+F12gGyF0DoYgOS7uZ4HDt6qpu9QXCUTVbqT+ht4m/0uhwogYbPAnZLqFpC9YF8OWb3RvtAgMBAAECggEAVxWTxdSwB5Bh6CBFTU87pI1gi4nxumlB2YG02A7XEQJ2dggRZ62lcNVqhrHc6R9vpkCPChfpapbQOlN41VBHcAIaYIG3oLdvy7rt//OqNnej3GUiAqM+C0hPgJFn7sb3d5fM1Wxb5qkqjHJhgjME8IPSIaCnQRpCII8QdXFQzfOkOebvLvvYKNTx8Ndy0cb7EuWhArDqqrszUPyDWW+D7mgz+5YDMWie8lwkMLkQRZ5kgeAIWN9K0mVTSkoauc7cC1ICQ2/l68+Mrc8fznKmkoqpm1TxUZ8VloQEttR61z8CElueXLg7fBb9f4rlFwJ9QGqbP3x5lbr9iDKMoytiAQKBgQDyZjiqvEjmDYJ8EORl3fGAGMTRmT3anmrJM37/NJ8iPiDXO28OnsemgbvonfRz6BDljUZh8xoXF4lZEJKw0SnPXOgFYPt6eLd881Isijq0mV4Wyu733l5vE/vFep5m08f1321R/6WJ7FPm9tyxdmaKtqnxecGlYJDzU5y+cyvgLQKBgQDQdkG/bazB6mor0y0S0sapj0/n0MC2STwRa3XG4FJTyHKqBwm1I64prxc9pLeAEOYnvj9oUELgaoe2Si/RT+xotqVpgmA28cLMcAUzLinbhlYsvXuKKV8c+z7cnfsGLj1b8kfpluw1u3VvjU0VQ0xIxrnDbZyt9Ueg2VIAwOPCwQKBgHHIL/Nc/G8YilaIa12xx8nUVpb4csNrNz8IsCVFYylktm+xk1juiVMMdNMlSfkaRswp+47A2U9bmfo3wFPFavXOa48SzhjYD3FUmg8UN6hMkZDrYy7wr60+WSGChFZKNQOiBCPId8D9MQkqeb/Hjyyvv6f8+jwRzxiY9+uiDkdlAoGAMIlIN6T2k1PcEoYhuX8/6BzJEwVkyUx14uxtSLfUE1PZdsMavIUpOOVeeOjQHM5SeDBwnP4LBCtpm8TcK1T7i0nza4SCmGhj3au7WjZGYql9iP85M2r8jUfmVAGof8DmYnEf00BjkQMrjaSNrQS1T0CN4fW0hEBWxBm1YR2IKkECgYEAo4D6iyaVkObA0sU+xOG+Ugz57jv3Uh4gTxzuPsfB9+sc9jHTkA87qU3cHQDj0JVfBgavYmPAp5k1f6H8XICxQHTr3vCy4WmMb0zwp98dtK+NMahI2pk/uPukOaqmYXT1zGMT0ZsteSSh/2PJKA9GMabmq3QIlRePEZ1a0Md4WgY=
  appId: 2018062660422282


weichat:
  appId: wx7570f2e03d6d90f5
  redirectUri: http://devappapi.zntyydh.com/auth/weixin/authcallback
  appSecret: 24bdc86540878d88dd9c20af87bb4744
  pay:
    mchId: 1508180271 
    apiKey: 3n1iMXSvlqVSAbpyCKqOtbRBJFZbvebb
    unifiedorder: https://api.mch.weixin.qq.com/pay/unifiedorder
    notifyUrl: http://devappapi.zntyydh.com/order/weichat/notify

    
    
 
 
---
#生产环境
spring:
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB    
  profiles: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.zntyydh.com:3306/sports?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: sports
    password: VbuQLFCyyr1VMs8
    initialize: true
    initial-size: 20
    max-active: 100
  redis:  
    password: ZNTY5lqUdYE7oA6C18
    pool:
      max-idle: 1000    
      min-idle: 200    
      max-active: 10000
      max-wait: 10000
    cluster:
      nodes: 
        - redis1.zntyydh.com:7000
        - redis2.zntyydh.com:7000
        - redis3.zntyydh.com:7000
        - redis4.zntyydh.com:7000
        - redis5.zntyydh.com:7000
        - redis6.zntyydh.com:7000 
  freemarker: 
    allow-request-override: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefer-file-system-access: false
    suffix: .html
  dubbo:
      protocol:
        name: dubbo
      application:
        name: sports
        owner: zoutao
      registry:
        address: zookeeper://zookeeper.zntyydh.com:9075
        port: 21804
      base-package: com.efida.sports.service.dubbo
      consumer:
        timeout: 20000 
        check: false                        # 服务启动时检查被调用服务是否可用
        retries: 2
        
weichat:
  appId: wx7570f2e03d6d90f5
  redirectUri: http://appapi.zntyydh.com/auth/weixin/authcallback
  appSecret: 24bdc86540878d88dd9c20af87bb4744
  pay:
    mchId: 1508180271 
    apiKey: 3n1iMXSvlqVSAbpyCKqOtbRBJFZbvebb
    unifiedorder: https://api.mch.weixin.qq.com/pay/unifiedorder
    notifyUrl: http://appapi.zntyydh.com/order/weichat/notify


ALiPay:
  partner: 2088031073324450
  notifyUrl: http://appapi.zntyydh.com/order/alipay/pay/callback
  returnUrl: http://appapi.zntyydh.com/order/alipay/gateway/
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxWMHag4uwCHMneanvb4ZtawTRimEnbIWp6cFoQNf2bGxImScLfXzsolVy3Jw908ANbEJAFPAxTHfQDkeF6HEL5ylRW7DRDgsXjqgtH3QhuDNTZ8f9djNHN3d1Pp2QOgYxytnwpmt0+HEF2r0OsI+5MEtyYU5BD7a/4hOGGq59atnAeegqtzpMRzBuXnR4IdC+juuLCiUp+KeKyV5DYyOmm/BragEBAMtRWAW/IHaWwS0pxgFqahB15iXgWkKVgLqltHsPGTTE15v02TPhddoBshdA6GIDku7meBw7eqqbvUFwlE1W6k/obeJv9LocKIGGzwJ2S6haQvWBfDlm90b7QIDAQAB
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDFYwdqDi7AIcyd5qe9vhm1rBNGKYSdshanpwWhA1/ZsbEiZJwt9fOyiVXLcnD3TwA1sQkAU8DFMd9AOR4XocQvnKVFbsNEOCxeOqC0fdCG4M1Nnx/12M0c3d3U+nZA6BjHK2fCma3T4cQXavQ6wj7kwS3JhTkEPtr/iE4Yarn1q2cB56Cq3OkxHMG5edHgh0L6O64sKJSn4p4rJXkNjI6ab8GtqAQEAy1FYBb8gdpbBLSnGAWpqEHXmJeBaQpWAuqW0ew8ZNMTXm/TZM+F12gGyF0DoYgOS7uZ4HDt6qpu9QXCUTVbqT+ht4m/0uhwogYbPAnZLqFpC9YF8OWb3RvtAgMBAAECggEAVxWTxdSwB5Bh6CBFTU87pI1gi4nxumlB2YG02A7XEQJ2dggRZ62lcNVqhrHc6R9vpkCPChfpapbQOlN41VBHcAIaYIG3oLdvy7rt//OqNnej3GUiAqM+C0hPgJFn7sb3d5fM1Wxb5qkqjHJhgjME8IPSIaCnQRpCII8QdXFQzfOkOebvLvvYKNTx8Ndy0cb7EuWhArDqqrszUPyDWW+D7mgz+5YDMWie8lwkMLkQRZ5kgeAIWN9K0mVTSkoauc7cC1ICQ2/l68+Mrc8fznKmkoqpm1TxUZ8VloQEttR61z8CElueXLg7fBb9f4rlFwJ9QGqbP3x5lbr9iDKMoytiAQKBgQDyZjiqvEjmDYJ8EORl3fGAGMTRmT3anmrJM37/NJ8iPiDXO28OnsemgbvonfRz6BDljUZh8xoXF4lZEJKw0SnPXOgFYPt6eLd881Isijq0mV4Wyu733l5vE/vFep5m08f1321R/6WJ7FPm9tyxdmaKtqnxecGlYJDzU5y+cyvgLQKBgQDQdkG/bazB6mor0y0S0sapj0/n0MC2STwRa3XG4FJTyHKqBwm1I64prxc9pLeAEOYnvj9oUELgaoe2Si/RT+xotqVpgmA28cLMcAUzLinbhlYsvXuKKV8c+z7cnfsGLj1b8kfpluw1u3VvjU0VQ0xIxrnDbZyt9Ueg2VIAwOPCwQKBgHHIL/Nc/G8YilaIa12xx8nUVpb4csNrNz8IsCVFYylktm+xk1juiVMMdNMlSfkaRswp+47A2U9bmfo3wFPFavXOa48SzhjYD3FUmg8UN6hMkZDrYy7wr60+WSGChFZKNQOiBCPId8D9MQkqeb/Hjyyvv6f8+jwRzxiY9+uiDkdlAoGAMIlIN6T2k1PcEoYhuX8/6BzJEwVkyUx14uxtSLfUE1PZdsMavIUpOOVeeOjQHM5SeDBwnP4LBCtpm8TcK1T7i0nza4SCmGhj3au7WjZGYql9iP85M2r8jUfmVAGof8DmYnEf00BjkQMrjaSNrQS1T0CN4fW0hEBWxBm1YR2IKkECgYEAo4D6iyaVkObA0sU+xOG+Ugz57jv3Uh4gTxzuPsfB9+sc9jHTkA87qU3cHQDj0JVfBgavYmPAp5k1f6H8XICxQHTr3vCy4WmMb0zwp98dtK+NMahI2pk/uPukOaqmYXT1zGMT0ZsteSSh/2PJKA9GMabmq3QIlRePEZ1a0Md4WgY=
  appId: 2018062660422282    
        
       
