# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：  
#   测试环境：java -jar xxx.jar --server.port=18080 --spring.profiles.active=test  
#   生产环境：java -jar xxx.jar --server.port=18080 --spring.profiles.active=prod
# dev  config
spring:
  profiles:  
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.115.40.84:23306/sports?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: sports
    password: VbuQLFCyyr1VMs8
    initialize: true
    initial-size: 20
    max-active: 100
  redis:
    host: 127.0.0.1
    password: 
    port: 6379
    pool:
      max-idle: 50    
      min-idle: 10    
      max-active: 5000
      max-wait: 10000
  freemarker: 
    allow-request-override: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefer-file-system-access: false
    suffix: .html
  dubbo:
      protocol:
        name: dubbo
      application:
        name: sports
        owner: zengbo
      registry:
        address: zookeeper://127.0.0.1:2181
        port: 21804
      base-package: com.efida.sports.service.dubbo
      consumer:
        timeout: 20000 
        check: false                        # 服务启动时检查被调用服务是否可用zookeeper://192.168.8.4:9075
        retries: 2
  static-path: http://localhost:9996        

runSycTask : false

mybatis-plus: 
  mapper-locations: classpath*:com/efida/sports/mapper/*.xml
  type-aliases-package: com.efida.sports.entity
  
server:  
  port: 9996

ALiPay:
  partner: 2088031073324450
  notifyUrl: http://29eq6v.natappfree.cc/order/alipay/pay/orderback
  returnUrl: http://29eq6v.natappfree.cc/order/alipay/gateway/
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCnxj/9qwVfgoUh/y2W89L6BkRAFljhNhgPdyPuBV64bfQNN1PjbCzkIM6qRdKBoLPXmKKMiFYnkd6rAoprih3/PrQEB/VsW8OoM8fxn67UDYuyBTqA23MML9q1+ilIZwBC2AQ2UBVOrFXfFl75p6/B5KsiNG9zpgmLCUYuLkxpLQIDAQAB
  privateKey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAOgtD1MQllxtxO4+4YGdgAYuqhGwYQm/cwvwQgf7PbZApJ3F3xXQH4xpibOxy11MTMAKAVFMWEDhPA8z23u2MsIpGDzIKURa7QNxGVietuT24X/6jP8OPpo2dvyWapQyVAq/4iiawIVurd5S7ivTgESErv7AFmD2EjkWWPL9tPWPAgMBAAECgYA2hY5ZtUV6AxUB1aZjJ7dOvFqXuNGw1lKP9SWsdiVxzRBbNIJEvxEJiicaGaBmEmrblf3lN4ZqBfpyn3zlOk4Es7xo1QXdqkZCCLf2rOjjxzunlC/qMjHS63rGHYiQlG+Tbg4YrpOtaa0ElhTGDD9t0Fkv8If3eUkAi/RilvJOcQJBAP+REjFXc+OsA7pASb0hibn9m3+HX7Q6r6jRtBKiEYK8wTpmBV1xeSkk+/e9NRqKx8YyAwbNWfZS+YO25nhrfGMCQQDokdYHyY1k/aiZ+JLGk6X036dnCT4KNEUWjM3y9Gw/EyXDmtUDrphGjxFYm2MYA+y6pUy8pZzzsi0524cPItvlAkEAnXAMShM61FWikjmKc5XWl5pxEbYeshO5JQHSsevfZ6/KRaSVx4PhBQTAqFSKA0jdWu5ySN12fzWMeqTRA/wLSwJBAJg4c90u96PlPshgYTkmBJZtGLWg4AFvytSCnn3pqzvxfWM04T2CtlpgY9saAVcDoptbfAlxYHRE58MZw6GNkF0CQQDyWBIkqfm16Ir/L4K0JVMXKMEgh+I37ZsV5ZuLy65kyCx6+C8/pdaYfXEfeHoO6U51LEydLp7h4hcBblIDe0wC
  appId: 2018061360368311
weichat:
  appId: wx8a7e91aab9880c89
  redirectUri: http://qingfeng.tunnel.qydev.com/auth/weixin/authcallback
  appSecret: 8fe83d7c15fca3931024145133b857b2
  pay:
    mchId: 1504399571
    apiKey: uNe35fEGrGmllWEyhCDwEgW5z8vkpUSQ
    unifiedorder: https://api.mch.weixin.qq.com/pay/unifiedorder
    notifyUrl: http://zntyweb.efida.com.cn/order/weichat/notify
qq:
  client_id: 101487198
  client_key: e9a0a4b3f0c132136f6c2f4a12ba1b87
  redirect_uri: http://qingfeng.tunnel.qydev.com/auth/qq/authcallback
weibo:
  client_id: 203713470
  client_secret: 2329be8161941570adcb4f0bb161d075
  redirect_uri: http://qingfeng.tunnel.qydev.com/auth/weibo/authcallback
  grant_type: authorization_code
  code: code    
sms:
  uid: 211591 
  pwd: e85619909747b13f8a53b90fb6655d07

ucenter-domain: http://ducenter.zntyydh.com
apply-domain: http://dpc.zntyydh.com
social-domain: http://dsof.zntyydh.com  
---
#测试环境 password: mysql (test VbuQLFCyyr1VMs8 dev DevVbuQLFCyyr1VMs8)   redis(test ZNTY5lqUdYE7oA6C18 dev DevZNTY5lqUdYE7oA6C18)  dubbo (test 172.16.3.23 dev zookeeper.zntyydh.com)
spring:  
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.zntyydh.com:3306/sports?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: sports
    password: DevVbuQLFCyyr1VMs8
    initialize: true
    initial-size: 20
    max-active: 100
  redis:  
    pool:
      max-idle: 50    
      min-idle: 10    
      max-active: 5000
      max-wait: 10000
    host: redis.zntyydh.com
    port: 7000
    password: DevZNTY5lqUdYE7oA6C18
  freemarker: 
    allow-request-override: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefer-file-system-access: false
    suffix: .html
  dubbo:
      protocol:
        name: dubbo
        host: zookeeper.zntyydh.com
        threads: 3000
        threadpool: cached 
      application:
        name: sports
        owner: zengbo
      registry:
        address: zookeeper://zookeeper.zntyydh.com:9075
        port: 21804
      base-package: com.efida.sports.service.dubbo
      consumer:
        timeout: 20000 
        check: false                        # 服务启动时检查被调用服务是否可用
        retries: 2    
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  static-path: http://zntyweb.efida.com.cn
weibo:
  redirect_uri: http://zntyweb.efida.com.cn/auth/weibo/authcallback
weichat:
  appId: wx2c615502e18dc389
  redirectUri: http://zntyweb.efida.com.cn/auth/weixin/authcallback
  appSecret: 4d0dbb9df6a01bccf9879dfd8a7990a1
  pay:
    mchId: 1508306401
    apiKey: bQoaBaJeg6DchMBxSFxN3pt6Jk6Ly1I9
    unifiedorder: https://api.mch.weixin.qq.com/pay/unifiedorder
    notifyUrl: http://zntyweb.efida.com.cn/order/weichat/notify
qq:
  client_id: 101487198
  client_key: e9a0a4b3f0c132136f6c2f4a12ba1b87
  redirect_uri: http://zntywx.efida.com.cn/auth/qq/authcallback                

ucenter-domain: http://devucenterweb.zntyydh.com
apply-domain: http://devsports.zntyydh.com
social-domain: http://devsof.zntyydh.com

--- 
#生产环境
spring:  
  profiles: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.zntyydh.com:3306/sports?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: sports
    password: VbuQLFCyyr1VMs8
    initialize: true
    initial-size: 20
    max-active: 100
  redis:
    pool:
      max-idle: 50
      min-idle: 10
      max-active: 5000
      max-wait: 10000
    timeout: 2000
    password: ZNTY5lqUdYE7oA6C18   
    cluster:
      max-redirects: 6
      nodes: 
        - redis1.zntyydh.com:7000
        - redis2.zntyydh.com:7000
        - redis3.zntyydh.com:7000
        - redis4.zntyydh.com:7000
        - redis5.zntyydh.com:7000
        - redis6.zntyydh.com:7000 
  freemarker: 
    allow-request-override: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefer-file-system-access: false
    suffix: .html
  dubbo:
      protocol:
        name: dubbo
        threads: 3000
        threadpool: cached 
      application:
        name: sports
        owner: zengbo
      registry:
        address: zookeeper://zookeeper.zntyydh.com:9075
        port: 21804
      base-package: com.efida.sports.service.dubbo
      consumer:
        timeout: 20000 
        check: false                        # 服务启动时检查被调用服务是否可用
        retries: 2
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  static-path: http://static.pc.zntyydh.com
weibo:
  redirect_uri: http://sports.zntyydh.com/auth/weibo/authcallback
weichat:
  appId: wx8a7e91aab9880c89
  redirectUri: http://sports.zntyydh.com/auth/weixin/authcallback
  appSecret: 8fe83d7c15fca3931024145133b857b2
  pay:
    mchId: 1504399571
    apiKey: uNe35fEGrGmllWEyhCDwEgW5z8vkpUSQ
    unifiedorder: https://api.mch.weixin.qq.com/pay/unifiedorder
    notifyUrl: http://sports.zntyydh.com/order/weichat/notify
qq:
  client_id: 101487198
  client_key: e9a0a4b3f0c132136f6c2f4a12ba1b87
  redirect_uri: http://sports.zntyydh.com/auth/qq/authcallback      

ucenter-domain: http://ucenter.zntyydh.com
apply-domain: http://sports.zntyydh.com
social-domain: http://sof.zntyydh.com
 