/**
 * efida.com.cn Inc.
 * Copyright (c) 2004-2018 All Rights Reserved.
 */
package com.efida.sport.dmp.facade.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * 
 * @author zhiyang
 * @version $Id: EnrollxInfoDto.java, v 0.1 2018年7月27日 下午12:56:20 zhiyang Exp $
 */
public class EnrollxInfoDto implements Serializable {
    /**  */
    private static final long   serialVersionUID = 1L;

    //申请编号，不需填充
    private String              applyCode;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.leader_name
     *
     * @mbggenerated
     */
    private String              leaderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.leader_phone
     *
     * @mbggenerated
     */
    private String              leaderPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.term_name
     *
     * @mbggenerated
     */
    private String              teamName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.event_type
     *
     * @mbggenerated
     */
    private String              eventType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column open_apply_info.registration_num
     *
     * @mbggenerated
     */
    private Integer             registrationNum;

    //项目编号（必选）
    private String              gameCode;
    //项目名称（ 必选）
    private String              gameName;
    //赛事编号  （必选）
    private String              matchCode;
    //赛事名称 （必选）
    private String              matchName;
    //分赛场编号 (可选)
    private String              fieldCode;
    //分赛场名称 （可选）
    private String              fieldName;

    //组别编号(可选)
    private String              matchGroupCode;
    //组别名称（可选）
    private String              matchGroupName;
    //项目细类编号（必选）
    private String              eventCode;
    //项目细类名称（必选）
    private String              eventName;

    //比赛项开始时间
    private Date                eventStartTime;
    //比赛项结束时间
    private Date                eventEndTime;
    //报名时间 （必填）
    private String              applyTime;

    //报名费（元）（ 必填）
    private Double              entryFee;

    /**
     * 修改标识
     */
    private boolean             modifyFlag       = false;
    //记录唯一性标识
    private String              idempotentId;

    //承办方
    private String              unitCode;
    /**
     * 渠道编号
     */
    private String              channelCode;

    //来源  0.来自内部系统 。 1来自交换系统接口
    private Byte                source           = 0;

    private List<PlayerInfoDto> playerData;

    public List<PlayerInfoDto> getPlayerData() {
        return playerData;
    }

    public void setPlayerData(List<PlayerInfoDto> playerData) {
        this.playerData = playerData;
    }

    public String getApplyCode() {
        return applyCode;
    }

    public void setApplyCode(String applyCode) {
        this.applyCode = applyCode;
    }

    public String getLeaderName() {
        return leaderName;
    }

    public void setLeaderName(String leaderName) {
        this.leaderName = leaderName;
    }

    public String getLeaderPhone() {
        return leaderPhone;
    }

    public void setLeaderPhone(String leaderPhone) {
        this.leaderPhone = leaderPhone;
    }

    public String getTeamName() {
        return teamName;
    }

    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    public String getEventType() {
        return eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public Integer getRegistrationNum() {
        return registrationNum;
    }

    public void setRegistrationNum(Integer registrationNum) {
        this.registrationNum = registrationNum;
    }

    public String getGameCode() {
        return gameCode;
    }

    public void setGameCode(String gameCode) {
        this.gameCode = gameCode;
    }

    public String getGameName() {
        return gameName;
    }

    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    public String getMatchCode() {
        return matchCode;
    }

    public void setMatchCode(String matchCode) {
        this.matchCode = matchCode;
    }

    public String getMatchName() {
        return matchName;
    }

    public void setMatchName(String matchName) {
        this.matchName = matchName;
    }

    public String getFieldCode() {
        return fieldCode;
    }

    public void setFieldCode(String fieldCode) {
        this.fieldCode = fieldCode;
    }

    public String getFieldName() {
        return fieldName;
    }

    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    public String getMatchGroupCode() {
        return matchGroupCode;
    }

    public void setMatchGroupCode(String matchGroupCode) {
        this.matchGroupCode = matchGroupCode;
    }

    public String getMatchGroupName() {
        return matchGroupName;
    }

    public void setMatchGroupName(String matchGroupName) {
        this.matchGroupName = matchGroupName;
    }

    public String getEventCode() {
        return eventCode;
    }

    public void setEventCode(String eventCode) {
        this.eventCode = eventCode;
    }

    public String getEventName() {
        return eventName;
    }

    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    public Date getEventStartTime() {
        return eventStartTime;
    }

    public void setEventStartTime(Date eventStartTime) {
        this.eventStartTime = eventStartTime;
    }

    public Date getEventEndTime() {
        return eventEndTime;
    }

    public void setEventEndTime(Date eventEndTime) {
        this.eventEndTime = eventEndTime;
    }

    public String getApplyTime() {
        return applyTime;
    }

    public void setApplyTime(String applyTime) {
        this.applyTime = applyTime;
    }

    public Double getEntryFee() {
        return entryFee;
    }

    public void setEntryFee(Double entryFee) {
        this.entryFee = entryFee;
    }

    public boolean isModifyFlag() {
        return modifyFlag;
    }

    public void setModifyFlag(boolean modifyFlag) {
        this.modifyFlag = modifyFlag;
    }

    public String getIdempotentId() {
        return idempotentId;
    }

    public void setIdempotentId(String idempotentId) {
        this.idempotentId = idempotentId;
    }

    public String getUnitCode() {
        return unitCode;
    }

    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }

    public String getChannelCode() {
        return channelCode;
    }

    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode;
    }

    public Byte getSource() {
        return source;
    }

    public void setSource(Byte source) {
        this.source = source;
    }

    @Override
    public String toString() {
        return "EnrollxInfoDto [applyCode=" + applyCode + ", leaderName=" + leaderName
               + ", leaderPhone=" + leaderPhone + ", teamName=" + teamName + ", eventType="
               + eventType + ", registrationNum=" + registrationNum + ", gameCode=" + gameCode
               + ", gameName=" + gameName + ", matchCode=" + matchCode + ", matchName=" + matchName
               + ", fieldCode=" + fieldCode + ", fieldName=" + fieldName + ", matchGroupCode="
               + matchGroupCode + ", matchGroupName=" + matchGroupName + ", eventCode=" + eventCode
               + ", eventName=" + eventName + ", eventStartTime=" + eventStartTime
               + ", eventEndTime=" + eventEndTime + ", applyTime=" + applyTime + ", entryFee="
               + entryFee + ", modifyFlag=" + modifyFlag + ", idempotentId=" + idempotentId
               + ", unitCode=" + unitCode + ", channelCode=" + channelCode + ", source=" + source
               + "]";
    }

}
