package com.efida.sports.entity;

import java.io.Serializable;
import java.util.Date;

import com.baomidou.mybatisplus.annotations.TableField;
import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.enums.IdType;

public class GoodsOrder implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.id
     *
     * @mbggenerated
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Long              id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.order_code
     *
     * @mbggenerated
     */
    private String            orderCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.register_code
     *
     * @mbggenerated
     */
    private String            registerCode;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.goods_code
     *
     * @mbggenerated
     */
    private String            goodsCode;

    private String            goodsTitle;
    private String            goodsPic;
    private String            payWayCode;
    private String            payWayName;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.goods_price
     *
     * @mbggenerated
     */
    private Integer           goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.goods_num
     *
     * @mbggenerated
     */
    private Integer           goodsNum;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.extra_money
     *
     * @mbggenerated
     */
    private Integer           extraMoney;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.order_price
     *
     * @mbggenerated
     */
    private Integer           orderPrice;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.order_status
     *
     * @mbggenerated
     */
    private String            orderStatus;

    private String            payOrderCode;
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.pay_time
     *
     * @mbggenerated
     */
    private Date              payTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.realname
     *
     * @mbggenerated
     */
    private String            realname;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.mobile
     *
     * @mbggenerated
     */
    private String            mobile;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.province
     *
     * @mbggenerated
     */
    private String            province;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.city
     *
     * @mbggenerated
     */
    private String            city;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.area
     *
     * @mbggenerated
     */
    private String            area;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.address
     *
     * @mbggenerated
     */
    private String            address;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.remark
     *
     * @mbggenerated
     */
    private String            remark;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.order_time
     *
     * @mbggenerated
     */
    private Date              orderTime;
    private Date              optTime;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.gmt_create
     *
     * @mbggenerated
     */
    private Date              gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column goods_order.gmt_modified
     *
     * @mbggenerated
     */
    private Date              gmtModified;

    /**
     * 登录手机号
     */
    @TableField(exist = false)
    private String            loginPhone;

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.id
     *
     * @return the value of goods_order.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.id
     *
     * @param id
     *            the value for goods_order.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.order_code
     *
     * @return the value of goods_order.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.order_code
     *
     * @param orderCode
     *            the value for goods_order.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.register_code
     *
     * @return the value of goods_order.register_code
     *
     * @mbggenerated
     */
    public String getRegisterCode() {
        return registerCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.register_code
     *
     * @param registerCode
     *            the value for goods_order.register_code
     *
     * @mbggenerated
     */
    public void setRegisterCode(String registerCode) {
        this.registerCode = registerCode == null ? null : registerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.goods_code
     *
     * @return the value of goods_order.goods_code
     *
     * @mbggenerated
     */
    public String getGoodsCode() {
        return goodsCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.goods_code
     *
     * @param goodsCode
     *            the value for goods_order.goods_code
     *
     * @mbggenerated
     */
    public void setGoodsCode(String goodsCode) {
        this.goodsCode = goodsCode == null ? null : goodsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.goods_price
     *
     * @return the value of goods_order.goods_price
     *
     * @mbggenerated
     */
    public Integer getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.goods_price
     *
     * @param goodsPrice
     *            the value for goods_order.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(Integer goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.goods_num
     *
     * @return the value of goods_order.goods_num
     *
     * @mbggenerated
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.goods_num
     *
     * @param goodsNum
     *            the value for goods_order.goods_num
     *
     * @mbggenerated
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.extra_money
     *
     * @return the value of goods_order.extra_money
     *
     * @mbggenerated
     */
    public Integer getExtraMoney() {
        return extraMoney;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.extra_money
     *
     * @param extraMoney
     *            the value for goods_order.extra_money
     *
     * @mbggenerated
     */
    public void setExtraMoney(Integer extraMoney) {
        this.extraMoney = extraMoney;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.order_price
     *
     * @return the value of goods_order.order_price
     *
     * @mbggenerated
     */
    public Integer getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.order_price
     *
     * @param orderPrice
     *            the value for goods_order.order_price
     *
     * @mbggenerated
     */
    public void setOrderPrice(Integer orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.order_status
     *
     * @return the value of goods_order.order_status
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.order_status
     *
     * @param orderStatus
     *            the value for goods_order.order_status
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.pay_time
     *
     * @return the value of goods_order.pay_time
     *
     * @mbggenerated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.pay_time
     *
     * @param payTime
     *            the value for goods_order.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.realname
     *
     * @return the value of goods_order.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.realname
     *
     * @param realname
     *            the value for goods_order.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.mobile
     *
     * @return the value of goods_order.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.mobile
     *
     * @param mobile
     *            the value for goods_order.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.province
     *
     * @return the value of goods_order.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.province
     *
     * @param province
     *            the value for goods_order.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.city
     *
     * @return the value of goods_order.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.city
     *
     * @param city
     *            the value for goods_order.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.area
     *
     * @return the value of goods_order.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.area
     *
     * @param area
     *            the value for goods_order.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.address
     *
     * @return the value of goods_order.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.address
     *
     * @param address
     *            the value for goods_order.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.remark
     *
     * @return the value of goods_order.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.remark
     *
     * @param remark
     *            the value for goods_order.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.order_time
     *
     * @return the value of goods_order.order_time
     *
     * @mbggenerated
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.order_time
     *
     * @param orderTime
     *            the value for goods_order.order_time
     *
     * @mbggenerated
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.gmt_create
     *
     * @return the value of goods_order.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.gmt_create
     *
     * @param gmtCreate
     *            the value for goods_order.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column goods_order.gmt_modified
     *
     * @return the value of goods_order.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column goods_order.gmt_modified
     *
     * @param gmtModified
     *            the value for goods_order.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getGoodsTitle() {
        return goodsTitle;
    }

    public void setGoodsTitle(String goodsTitle) {
        this.goodsTitle = goodsTitle;
    }

    public String getGoodsPic() {
        return goodsPic;
    }

    public void setGoodsPic(String goodsPic) {
        this.goodsPic = goodsPic;
    }

    public String getPayOrderCode() {
        return payOrderCode;
    }

    public void setPayOrderCode(String payOrderCode) {
        this.payOrderCode = payOrderCode;
    }

    public String getPayWayCode() {
        return payWayCode;
    }

    public void setPayWayCode(String payWayCode) {
        this.payWayCode = payWayCode;
    }

    public String getPayWayName() {
        return payWayName;
    }

    public void setPayWayName(String payWayName) {
        this.payWayName = payWayName;
    }

    public Date getOptTime() {
        return optTime;
    }

    public void setOptTime(Date optTime) {
        this.optTime = optTime;
    }

    public String getLoginPhone() {
        return loginPhone;
    }

    public void setLoginPhone(String loginPhone) {
        this.loginPhone = loginPhone;
    }

}