package com.efida.sports.entity;

import java.io.Serializable;
import java.util.Date;

import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.enums.IdType;

public class UserAddress implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_address.id
	 *
	 * @mbggenerated
	 */
	@TableId(value = "id", type = IdType.AUTO)
	private Long id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_address.address_code
	 *
	 * @mbggenerated
	 */
	private String addressCode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_address.register_code
	 *
	 * @mbggenerated
	 */
	private String registerCode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_address.realname
	 *
	 * @mbggenerated
	 */
	private String realname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_address.mobile
	 *
	 * @mbggenerated
	 */
	private String mobile;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_address.province
	 *
	 * @mbggenerated
	 */
	private String province;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_address.city
	 *
	 * @mbggenerated
	 */
	private String city;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_address.area
	 *
	 * @mbggenerated
	 */
	private String area;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_address.address
	 *
	 * @mbggenerated
	 */
	private String address;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_address.isdefault
	 *
	 * @mbggenerated
	 */
	private Boolean isdefault;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_address.create_time
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_address.gmt_create
	 *
	 * @mbggenerated
	 */
	private Date gmtCreate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column user_address.gmt_modified
	 *
	 * @mbggenerated
	 */
	private Date gmtModified;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_address.id
	 *
	 * @return the value of user_address.id
	 *
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_address.id
	 *
	 * @param id
	 *            the value for user_address.id
	 *
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_address.address_code
	 *
	 * @return the value of user_address.address_code
	 *
	 * @mbggenerated
	 */
	public String getAddressCode() {
		return addressCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_address.address_code
	 *
	 * @param addressCode
	 *            the value for user_address.address_code
	 *
	 * @mbggenerated
	 */
	public void setAddressCode(String addressCode) {
		this.addressCode = addressCode == null ? null : addressCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_address.register_code
	 *
	 * @return the value of user_address.register_code
	 *
	 * @mbggenerated
	 */
	public String getRegisterCode() {
		return registerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_address.register_code
	 *
	 * @param registerCode
	 *            the value for user_address.register_code
	 *
	 * @mbggenerated
	 */
	public void setRegisterCode(String registerCode) {
		this.registerCode = registerCode == null ? null : registerCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_address.realname
	 *
	 * @return the value of user_address.realname
	 *
	 * @mbggenerated
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_address.realname
	 *
	 * @param realname
	 *            the value for user_address.realname
	 *
	 * @mbggenerated
	 */
	public void setRealname(String realname) {
		this.realname = realname == null ? null : realname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_address.mobile
	 *
	 * @return the value of user_address.mobile
	 *
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_address.mobile
	 *
	 * @param mobile
	 *            the value for user_address.mobile
	 *
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_address.province
	 *
	 * @return the value of user_address.province
	 *
	 * @mbggenerated
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_address.province
	 *
	 * @param province
	 *            the value for user_address.province
	 *
	 * @mbggenerated
	 */
	public void setProvince(String province) {
		this.province = province == null ? null : province.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_address.city
	 *
	 * @return the value of user_address.city
	 *
	 * @mbggenerated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_address.city
	 *
	 * @param city
	 *            the value for user_address.city
	 *
	 * @mbggenerated
	 */
	public void setCity(String city) {
		this.city = city == null ? null : city.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_address.area
	 *
	 * @return the value of user_address.area
	 *
	 * @mbggenerated
	 */
	public String getArea() {
		return area;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_address.area
	 *
	 * @param area
	 *            the value for user_address.area
	 *
	 * @mbggenerated
	 */
	public void setArea(String area) {
		this.area = area == null ? null : area.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_address.address
	 *
	 * @return the value of user_address.address
	 *
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_address.address
	 *
	 * @param address
	 *            the value for user_address.address
	 *
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_address.isdefault
	 *
	 * @return the value of user_address.isdefault
	 *
	 * @mbggenerated
	 */
	public Boolean getIsdefault() {
		return isdefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_address.isdefault
	 *
	 * @param isdefault
	 *            the value for user_address.isdefault
	 *
	 * @mbggenerated
	 */
	public void setIsdefault(Boolean isdefault) {
		this.isdefault = isdefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_address.create_time
	 *
	 * @return the value of user_address.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_address.create_time
	 *
	 * @param createTime
	 *            the value for user_address.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_address.gmt_create
	 *
	 * @return the value of user_address.gmt_create
	 *
	 * @mbggenerated
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_address.gmt_create
	 *
	 * @param gmtCreate
	 *            the value for user_address.gmt_create
	 *
	 * @mbggenerated
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user_address.gmt_modified
	 *
	 * @return the value of user_address.gmt_modified
	 *
	 * @mbggenerated
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user_address.gmt_modified
	 *
	 * @param gmtModified
	 *            the value for user_address.gmt_modified
	 *
	 * @mbggenerated
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
}