package com.efida.sports.cert.dao.entity;

import java.util.Date;

public class ScoreCertPicEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_pic.id
     *
     * @mbggenerated
     */
    private Long    id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_pic.pic_code
     *
     * @mbggenerated
     */
    private String  picCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_pic.cert_sn
     *
     * @mbggenerated
     */
    private String  certSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_pic.cert_pic_url
     *
     * @mbggenerated
     */
    private String  certPicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_pic.cert_short_pic_url
     *
     * @mbggenerated
     */
    private String  certShortPicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_pic.generate_pic_time
     *
     * @mbggenerated
     */
    private Date    generatePicTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_pic.is_delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_pic.is_fastdfs_delete
     *
     * @mbggenerated
     */
    private Boolean isFastdfsDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_pic.gmt_create
     *
     * @mbggenerated
     */
    private Date    gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_cert_pic.gmt_modified
     *
     * @mbggenerated
     */
    private Date    gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_pic.id
     *
     * @return the value of score_cert_pic.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_pic.id
     *
     * @param id the value for score_cert_pic.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_pic.pic_code
     *
     * @return the value of score_cert_pic.pic_code
     *
     * @mbggenerated
     */
    public String getPicCode() {
        return picCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_pic.pic_code
     *
     * @param picCode the value for score_cert_pic.pic_code
     *
     * @mbggenerated
     */
    public void setPicCode(String picCode) {
        this.picCode = picCode == null ? null : picCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_pic.cert_sn
     *
     * @return the value of score_cert_pic.cert_sn
     *
     * @mbggenerated
     */
    public String getCertSn() {
        return certSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_pic.cert_sn
     *
     * @param certSn the value for score_cert_pic.cert_sn
     *
     * @mbggenerated
     */
    public void setCertSn(String certSn) {
        this.certSn = certSn == null ? null : certSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_pic.cert_pic_url
     *
     * @return the value of score_cert_pic.cert_pic_url
     *
     * @mbggenerated
     */
    public String getCertPicUrl() {
        return certPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_pic.cert_pic_url
     *
     * @param certPicUrl the value for score_cert_pic.cert_pic_url
     *
     * @mbggenerated
     */
    public void setCertPicUrl(String certPicUrl) {
        this.certPicUrl = certPicUrl == null ? null : certPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_pic.cert_short_pic_url
     *
     * @return the value of score_cert_pic.cert_short_pic_url
     *
     * @mbggenerated
     */
    public String getCertShortPicUrl() {
        return certShortPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_pic.cert_short_pic_url
     *
     * @param certShortPicUrl the value for score_cert_pic.cert_short_pic_url
     *
     * @mbggenerated
     */
    public void setCertShortPicUrl(String certShortPicUrl) {
        this.certShortPicUrl = certShortPicUrl == null ? null : certShortPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_pic.generate_pic_time
     *
     * @return the value of score_cert_pic.generate_pic_time
     *
     * @mbggenerated
     */
    public Date getGeneratePicTime() {
        return generatePicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_pic.generate_pic_time
     *
     * @param generatePicTime the value for score_cert_pic.generate_pic_time
     *
     * @mbggenerated
     */
    public void setGeneratePicTime(Date generatePicTime) {
        this.generatePicTime = generatePicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_pic.is_delete
     *
     * @return the value of score_cert_pic.is_delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_pic.is_delete
     *
     * @param isDelete the value for score_cert_pic.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_pic.is_fastdfs_delete
     *
     * @return the value of score_cert_pic.is_fastdfs_delete
     *
     * @mbggenerated
     */
    public Boolean getIsFastdfsDelete() {
        return isFastdfsDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_pic.is_fastdfs_delete
     *
     * @param isFastdfsDelete the value for score_cert_pic.is_fastdfs_delete
     *
     * @mbggenerated
     */
    public void setIsFastdfsDelete(Boolean isFastdfsDelete) {
        this.isFastdfsDelete = isFastdfsDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_pic.gmt_create
     *
     * @return the value of score_cert_pic.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_pic.gmt_create
     *
     * @param gmtCreate the value for score_cert_pic.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_cert_pic.gmt_modified
     *
     * @return the value of score_cert_pic.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_cert_pic.gmt_modified
     *
     * @param gmtModified the value for score_cert_pic.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}