# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：  
#   开发环境：java -jar sports-web-1.0.0.jar --server.port=9999 --spring.profiles.active=dev
#   测试环境：java -jar xxx.jar --server.port=18080 --spring.profiles.active=test  
#   生产环境：java -jar xxx.jar --server.port=18080 --spring.profiles.active=prod
# dev  config
spring:
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB  
  profiles:  
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.8.4:3306/sport?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: 4ladGAjWGkk7Q
#    url: jdbc:mysql://127.0.0.1:3306/sports?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: 963852741
    url: jdbc:mysql://122.115.40.84:23306/sports?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: sports
    password: VbuQLFCyyr1VMs8
    initialize: true
    initial-size: 20
    max-active: 100
  redis:  
    pool:
      max-idle: 50    
      min-idle: 10    
      max-active: 5000
      max-wait: 10000
    host: 127.0.0.1
    port: 6379
  freemarker: 
    allow-request-override: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefer-file-system-access: false
    suffix: .html
  dubbo:
      protocol:
        name: dubbo
      application:
        name: sports
        owner: zoutao
      registry:
        address: zookeeper://127.0.0.1:2181
        port: 21804
      base-package: com.efida.sports.service.dubbo
      consumer:
        timeout: 20000 
        check: false                        # 服务启动时检查被调用服务是否可用
        retries: 2
#  static-path: http://192.168.0.42:9999
#  static-path: http://192.168.10.18:9999
  static-path: http://127.0.0.1:9999
  scoreCert:
      isConfigFirst: false
#logging:
#  level:
#    com.efida.sports.mapper : debug
runSycTask : true

mybatis-plus: 
  mapper-locations: classpath*:com/efida/sports/mapper/*.xml
  type-aliases-package: com.efida.sports.entity
  
server:  
  port: 9999
  tomcat:
    max-threads: 2000
    
ALiPay:
  partner: 2088131027600963
  notifyUrl: http://29eq6v.natappfree.cc/order/alipay/pay/orderback
  returnUrl: http://29eq6v.natappfree.cc/order/alipay/gateway/
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm8GB0Sk9Ge6bsg8cfIfUux5Afmy0Ry2dhcnNmsPV97IWY9PAyQ/E5yDe6skQZneP/GK8KnPQgZ+5qsuF8KKBdChYEeqYWHIxvM0DOaZxu90RoiAULBLjuw+b4VxUPN9MKDgz/uFhM2HG53wJs7as49U1TCa2y/I48SjyLEOoKI56Lou/8VFPX/LpTjkTYCKzED2rfP3rfqOeacTY0rgVWFmqG9BTrT0NwcKCbFwnv7tQT+jK/tWzZg/8SBbK15rkszsPRMhsanB8K4kOUlG3xLklpdsgnsMVbRo5+2MliwEFXcT7jD3lYbUTr+VOK0D5WQdi5Nv8q2EstrVICwjmWwIDAQAB
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCbwYHRKT0Z7puyDxx8h9S7HkB+bLRHLZ2Fyc2aw9X3shZj08DJD8TnIN7qyRBmd4/8Yrwqc9CBn7mqy4XwooF0KFgR6phYcjG8zQM5pnG73RGiIBQsEuO7D5vhXFQ830woODP+4WEzYcbnfAmztqzj1TVMJrbL8jjxKPIsQ6gojnoui7/xUU9f8ulOORNgIrMQPat8/et+o55pxNjSuBVYWaob0FOtPQ3BwoJsXCe/u1BP6Mr+1bNmD/xIFsrXmuSzOw9EyGxqcHwriQ5SUbfEuSWl2yCewxVtGjn7YyWLAQVdxPuMPeVhtROv5U4rQPlZB2Lk2/yrYSy2tUgLCOZbAgMBAAECggEALWGhSGcClYavOJ8shqAw/GAhHHThxgdlaTDWRiyfMC9kVKvC9RIyJcGvEauJqsFVY40FFD1wWARI3Zm1Kdq/ay/CEV5QCx0inscBFJAJfVo5JArCteC/F6bBnVUAekf5cZKGm9HhN05a3OGIFiO4lh1uDQUOp7eonaN3hCwmV8JPPG2QFSbgj+/eMzcs6//e0rGmUd7BFwkAaLzcyeFhANosvNyOf1P3sscmAvvjXqTka9U+5YNSERFvVEwi6NjrwxC6wEeJnCLZylIxPWXNJebpGFDdvP+vheBCKJjfmzM34jxkIvzIfNceNhP84/L1O/iQrnuI4WHe8ZcvZPDu0QKBgQDIFjv+V8ePvbE6Z8UAIrHz+DSXgIUoXnDjD4rLKFfEtY7pISt7AWpDaFpG3nesgPygra+iYzYdz8CMmMU5IyLqL5pu9IomWAMHmVA1ZYEDldOcCJ7G41xVt1kQh5ed+qoefhYYkqOBOnnhyZRsSAmbQiDVO0n5dijsLhpIJkmKkwKBgQDHR+9Gb8pRnw9dv6ZH/invVjxpdcYsOSxsvUV+3+79eKp54hQ5WRyNsAQkMrcYXSk6VESf++TErfPxpwpdGPQra/wkeeFk2Dkd5Ra7uxpTav9z4QUx4DlHqMejCgeP0kMnGVP8ClXuNOJtxWnRtOKKi/857H5TorA5TR5RZBDqGQKBgQCjkQGUR5/9Er46F7CFDtfYsHQV0duJB8NS61a0A5PUW/OrAxGvaZW76ye5vY2peHyMwc/NeTs5HaeziAPaVK3rMeUWhVQWSmaXpK5cKFFSY/3sFWPvBNhrvgnSKHY6kDrX2I0po16EexA+EvMBndY0lNeQWPp9Myn7ASk9CAegfwKBgD4PvwrWodGNkcGGgAiHtROeba4CSbdYDufGgjAjGVDDFYRjzhyWDfhqSr/jM3ZY/Q/3Um/oiLRf4Erv1KBttw0W0i2h73nyhMc0o0HP4UD9X5T9DRsdU3lnrNSvuO8nclZo4ujpZx2KRsIc6vmuNackNlYZurXdQrh1te1vFn1xAoGAQgwPW8UVVwzsl1aocSqgT85S2UxHyEp2qJQcPvA/aTh7lavDfCgUnb4pCzEorEBfk/XXdJCbiz6Q6Mjx5zib6of7z0dE8V+zW8VoMM+eyfD9MbYbrlIsGSw/Ge+TidPdjmSBRIwjEum2VK9+sicFykF/zX6z+INTv4GgLGR+LXI=
  appId: 2018051260127404
weichat:
  #  appId: wxe3957d8010639554
  #  redirectUri: http://devwx.zntyydh.com/auth/weixin/authcallback
  #  appSecret: 8a88c3f0148e65b13ac84b173225954d
  appId: wx2c615502e18dc389
  redirectUri: https://znty.bqj.cn/auth/weixin/authcallback
  appSecret: 4d0dbb9df6a01bccf9879dfd8a7990a1
  pay:
  #    mchId: 1504399571
  #    apiKey: uNe35fEGrGmllWEyhCDwEgW5z8vkpUSQ
  #    notifyUrl: http://devwx.zntyydh.com/order/weichat/notify
    mchId: 1508306401
    apiKey: bQoaBaJeg6DchMBxSFxN3pt6Jk6Ly1I9
    notifyUrl: https://znty.bqj.cn/order/weichat/notify
    unifiedorder: https://api.mch.weixin.qq.com/pay/unifiedorder
sms:
  uid: 211591 
  pwd: e85619909747b13f8a53b90fb6655d07 
ucenter-domain: http://ducenter.zntyydh.com
apply-domain: http://dwx.zntyydh.com
social-domain: http://dsof.zntyydh.com   
---
#测试环境
spring:
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.zntyydh.com:3306/sports?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: sports
    password: DevVbuQLFCyyr1VMs8
    initialize: true
    initial-size: 20
    max-active: 100
  redis:  
    pool:
      max-idle: 50    
      min-idle: 10    
      max-active: 5000
      max-wait: 10000
    host: redis.zntyydh.com
    port: 7000
    password: DevZNTY5lqUdYE7oA6C18
  freemarker: 
    allow-request-override: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefer-file-system-access: false
    suffix: .html
  dubbo:
      protocol:
        name: dubbo
        threads: 3000
        threadpool: cached 
      application:
        name: sports
        owner: zoutao
      registry:
        address: zookeeper://zookeeper.zntyydh.com:9075
        port: 21804
      base-package: com.efida.sports.service.dubbo
      consumer:
        timeout: 20000 
        check: false                        # 服务启动时检查被调用服务是否可用
        retries: 2
  #static-path: http://static.wx.zntyydh.com
  static-path: http://devwx.zntyydh.com
  scoreCert:
      isConfigFirst: false

ALiPay:
  partner: 2088131027600963
  notifyUrl: http://29eq6v.natappfree.cc/order/alipay/pay/orderback
  returnUrl: http://29eq6v.natappfree.cc/order/alipay/gateway/
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm8GB0Sk9Ge6bsg8cfIfUux5Afmy0Ry2dhcnNmsPV97IWY9PAyQ/E5yDe6skQZneP/GK8KnPQgZ+5qsuF8KKBdChYEeqYWHIxvM0DOaZxu90RoiAULBLjuw+b4VxUPN9MKDgz/uFhM2HG53wJs7as49U1TCa2y/I48SjyLEOoKI56Lou/8VFPX/LpTjkTYCKzED2rfP3rfqOeacTY0rgVWFmqG9BTrT0NwcKCbFwnv7tQT+jK/tWzZg/8SBbK15rkszsPRMhsanB8K4kOUlG3xLklpdsgnsMVbRo5+2MliwEFXcT7jD3lYbUTr+VOK0D5WQdi5Nv8q2EstrVICwjmWwIDAQAB
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCbwYHRKT0Z7puyDxx8h9S7HkB+bLRHLZ2Fyc2aw9X3shZj08DJD8TnIN7qyRBmd4/8Yrwqc9CBn7mqy4XwooF0KFgR6phYcjG8zQM5pnG73RGiIBQsEuO7D5vhXFQ830woODP+4WEzYcbnfAmztqzj1TVMJrbL8jjxKPIsQ6gojnoui7/xUU9f8ulOORNgIrMQPat8/et+o55pxNjSuBVYWaob0FOtPQ3BwoJsXCe/u1BP6Mr+1bNmD/xIFsrXmuSzOw9EyGxqcHwriQ5SUbfEuSWl2yCewxVtGjn7YyWLAQVdxPuMPeVhtROv5U4rQPlZB2Lk2/yrYSy2tUgLCOZbAgMBAAECggEALWGhSGcClYavOJ8shqAw/GAhHHThxgdlaTDWRiyfMC9kVKvC9RIyJcGvEauJqsFVY40FFD1wWARI3Zm1Kdq/ay/CEV5QCx0inscBFJAJfVo5JArCteC/F6bBnVUAekf5cZKGm9HhN05a3OGIFiO4lh1uDQUOp7eonaN3hCwmV8JPPG2QFSbgj+/eMzcs6//e0rGmUd7BFwkAaLzcyeFhANosvNyOf1P3sscmAvvjXqTka9U+5YNSERFvVEwi6NjrwxC6wEeJnCLZylIxPWXNJebpGFDdvP+vheBCKJjfmzM34jxkIvzIfNceNhP84/L1O/iQrnuI4WHe8ZcvZPDu0QKBgQDIFjv+V8ePvbE6Z8UAIrHz+DSXgIUoXnDjD4rLKFfEtY7pISt7AWpDaFpG3nesgPygra+iYzYdz8CMmMU5IyLqL5pu9IomWAMHmVA1ZYEDldOcCJ7G41xVt1kQh5ed+qoefhYYkqOBOnnhyZRsSAmbQiDVO0n5dijsLhpIJkmKkwKBgQDHR+9Gb8pRnw9dv6ZH/invVjxpdcYsOSxsvUV+3+79eKp54hQ5WRyNsAQkMrcYXSk6VESf++TErfPxpwpdGPQra/wkeeFk2Dkd5Ra7uxpTav9z4QUx4DlHqMejCgeP0kMnGVP8ClXuNOJtxWnRtOKKi/857H5TorA5TR5RZBDqGQKBgQCjkQGUR5/9Er46F7CFDtfYsHQV0duJB8NS61a0A5PUW/OrAxGvaZW76ye5vY2peHyMwc/NeTs5HaeziAPaVK3rMeUWhVQWSmaXpK5cKFFSY/3sFWPvBNhrvgnSKHY6kDrX2I0po16EexA+EvMBndY0lNeQWPp9Myn7ASk9CAegfwKBgD4PvwrWodGNkcGGgAiHtROeba4CSbdYDufGgjAjGVDDFYRjzhyWDfhqSr/jM3ZY/Q/3Um/oiLRf4Erv1KBttw0W0i2h73nyhMc0o0HP4UD9X5T9DRsdU3lnrNSvuO8nclZo4ujpZx2KRsIc6vmuNackNlYZurXdQrh1te1vFn1xAoGAQgwPW8UVVwzsl1aocSqgT85S2UxHyEp2qJQcPvA/aTh7lavDfCgUnb4pCzEorEBfk/XXdJCbiz6Q6Mjx5zib6of7z0dE8V+zW8VoMM+eyfD9MbYbrlIsGSw/Ge+TidPdjmSBRIwjEum2VK9+sicFykF/zX6z+INTv4GgLGR+LXI=
  appId: 2018051260127404
weichat:
#  appId: wxe3957d8010639554
#  redirectUri: http://devwx.zntyydh.com/auth/weixin/authcallback
#  appSecret: 8a88c3f0148e65b13ac84b173225954d
  appId: wx2c615502e18dc389
  redirectUri: http://devwx.zntyydh.com/auth/weixin/authcallback
  appSecret: 4d0dbb9df6a01bccf9879dfd8a7990a1
  pay:
#    mchId: 1504399571
#    apiKey: uNe35fEGrGmllWEyhCDwEgW5z8vkpUSQ
#    notifyUrl: http://devwx.zntyydh.com/order/weichat/notify
    mchId: 1508306401
    apiKey: bQoaBaJeg6DchMBxSFxN3pt6Jk6Ly1I9
    notifyUrl: http://devwx.zntyydh.com/order/weichat/notify
    unifiedorder: https://api.mch.weixin.qq.com/pay/unifiedorder
ucenter-domain: http://devucenterweb.zntyydh.com
apply-domain: http://devwx.zntyydh.com
social-domain: http://devsof.zntyydh.com    
--- 
#生产环境
spring:
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql.zntyydh.com:3306/sports?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: sports
    password: VbuQLFCyyr1VMs8
    initialize: true
    initial-size: 20
    max-active: 100
  redis:
    pool:
      max-idle: 50
      min-idle: 10
      max-active: 5000
      max-wait: 10000
    timeout: 2000
    password: ZNTY5lqUdYE7oA6C18   
    cluster:
      max-redirects: 6
      nodes: 
        - redis1.zntyydh.com:7000
        - redis2.zntyydh.com:7000
        - redis3.zntyydh.com:7000
        - redis4.zntyydh.com:7000
        - redis5.zntyydh.com:7000
        - redis6.zntyydh.com:7000 
  freemarker: 
    allow-request-override: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    prefer-file-system-access: false
    suffix: .html
  dubbo:
      protocol:
        name: dubbo
        threads: 3000
        threadpool: cached 
      application:
        name: sports
        owner: zoutao
      registry:
        address: zookeeper://zookeeper.zntyydh.com:9075
        port: 21804
      base-package: com.efida.sports.service.dubbo
      consumer:
        timeout: 20000 
        check: false                        # 服务启动时检查被调用服务是否可用
        retries: 2
  static-path: http://static.wx.zntyydh.com
  scoreCert:
      isConfigFirst: true
ALiPay:
  partner: 2088131027600963
  notifyUrl: http://wx.zntyydh.com/order/alipay/pay/orderback
  returnUrl: http://wx.zntyydh.com/order/alipay/gateway/
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm8GB0Sk9Ge6bsg8cfIfUux5Afmy0Ry2dhcnNmsPV97IWY9PAyQ/E5yDe6skQZneP/GK8KnPQgZ+5qsuF8KKBdChYEeqYWHIxvM0DOaZxu90RoiAULBLjuw+b4VxUPN9MKDgz/uFhM2HG53wJs7as49U1TCa2y/I48SjyLEOoKI56Lou/8VFPX/LpTjkTYCKzED2rfP3rfqOeacTY0rgVWFmqG9BTrT0NwcKCbFwnv7tQT+jK/tWzZg/8SBbK15rkszsPRMhsanB8K4kOUlG3xLklpdsgnsMVbRo5+2MliwEFXcT7jD3lYbUTr+VOK0D5WQdi5Nv8q2EstrVICwjmWwIDAQAB
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCbwYHRKT0Z7puyDxx8h9S7HkB+bLRHLZ2Fyc2aw9X3shZj08DJD8TnIN7qyRBmd4/8Yrwqc9CBn7mqy4XwooF0KFgR6phYcjG8zQM5pnG73RGiIBQsEuO7D5vhXFQ830woODP+4WEzYcbnfAmztqzj1TVMJrbL8jjxKPIsQ6gojnoui7/xUU9f8ulOORNgIrMQPat8/et+o55pxNjSuBVYWaob0FOtPQ3BwoJsXCe/u1BP6Mr+1bNmD/xIFsrXmuSzOw9EyGxqcHwriQ5SUbfEuSWl2yCewxVtGjn7YyWLAQVdxPuMPeVhtROv5U4rQPlZB2Lk2/yrYSy2tUgLCOZbAgMBAAECggEALWGhSGcClYavOJ8shqAw/GAhHHThxgdlaTDWRiyfMC9kVKvC9RIyJcGvEauJqsFVY40FFD1wWARI3Zm1Kdq/ay/CEV5QCx0inscBFJAJfVo5JArCteC/F6bBnVUAekf5cZKGm9HhN05a3OGIFiO4lh1uDQUOp7eonaN3hCwmV8JPPG2QFSbgj+/eMzcs6//e0rGmUd7BFwkAaLzcyeFhANosvNyOf1P3sscmAvvjXqTka9U+5YNSERFvVEwi6NjrwxC6wEeJnCLZylIxPWXNJebpGFDdvP+vheBCKJjfmzM34jxkIvzIfNceNhP84/L1O/iQrnuI4WHe8ZcvZPDu0QKBgQDIFjv+V8ePvbE6Z8UAIrHz+DSXgIUoXnDjD4rLKFfEtY7pISt7AWpDaFpG3nesgPygra+iYzYdz8CMmMU5IyLqL5pu9IomWAMHmVA1ZYEDldOcCJ7G41xVt1kQh5ed+qoefhYYkqOBOnnhyZRsSAmbQiDVO0n5dijsLhpIJkmKkwKBgQDHR+9Gb8pRnw9dv6ZH/invVjxpdcYsOSxsvUV+3+79eKp54hQ5WRyNsAQkMrcYXSk6VESf++TErfPxpwpdGPQra/wkeeFk2Dkd5Ra7uxpTav9z4QUx4DlHqMejCgeP0kMnGVP8ClXuNOJtxWnRtOKKi/857H5TorA5TR5RZBDqGQKBgQCjkQGUR5/9Er46F7CFDtfYsHQV0duJB8NS61a0A5PUW/OrAxGvaZW76ye5vY2peHyMwc/NeTs5HaeziAPaVK3rMeUWhVQWSmaXpK5cKFFSY/3sFWPvBNhrvgnSKHY6kDrX2I0po16EexA+EvMBndY0lNeQWPp9Myn7ASk9CAegfwKBgD4PvwrWodGNkcGGgAiHtROeba4CSbdYDufGgjAjGVDDFYRjzhyWDfhqSr/jM3ZY/Q/3Um/oiLRf4Erv1KBttw0W0i2h73nyhMc0o0HP4UD9X5T9DRsdU3lnrNSvuO8nclZo4ujpZx2KRsIc6vmuNackNlYZurXdQrh1te1vFn1xAoGAQgwPW8UVVwzsl1aocSqgT85S2UxHyEp2qJQcPvA/aTh7lavDfCgUnb4pCzEorEBfk/XXdJCbiz6Q6Mjx5zib6of7z0dE8V+zW8VoMM+eyfD9MbYbrlIsGSw/Ge+TidPdjmSBRIwjEum2VK9+sicFykF/zX6z+INTv4GgLGR+LXI=
  appId: 2018051260127404
weichat:
  appId: wxe3957d8010639554
  redirectUri: http://wx.zntyydh.com/auth/weixin/authcallback
  appSecret: 8a88c3f0148e65b13ac84b173225954d
  pay:
    mchId: 1504399571
    apiKey: uNe35fEGrGmllWEyhCDwEgW5z8vkpUSQ
    unifiedorder: https://api.mch.weixin.qq.com/pay/unifiedorder
    notifyUrl: http://wx.zntyydh.com/order/weichat/notify   
ucenter-domain: http://ucenter.zntyydh.com/
apply-domain: http://wx.zntyydh.com
social-domain: http://sof.zntyydh.com   