package com.efida.sports.dmp.dao.mapper;

import com.efida.sports.dmp.dao.entity.OpenLogContentEntity;

public interface OpenLogContentEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_log_content
     *
     * @mbggenerated
     */
    int insert(OpenLogContentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_log_content
     *
     * @mbggenerated
     */
    int insertSelective(OpenLogContentEntity record);

}