package com.efida.sports.dmp.dao.mapper;

import java.util.List;

import com.efida.sports.dmp.dao.entity.OpenPlayerEntity;

public interface OpenPlayerEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_player
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     *
     * 
     * @param applyCode
     * @return
     */
    int deleteByApplyCode(String applyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_player
     *
     * @mbggenerated
     */
    int insert(OpenPlayerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_player
     *
     * @mbggenerated
     */
    int insertSelective(OpenPlayerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_player
     *
     * @mbggenerated
     */
    OpenPlayerEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_player
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OpenPlayerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_player
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OpenPlayerEntity record);

    List<OpenPlayerEntity> selectByApplyCodes(List<String> applyCodes);

    List<OpenPlayerEntity> selectPlayerByApplyCode(String applyCode);

    List<OpenPlayerEntity> selectUnCleanPlayers();

    void updateCleanStatus(Long id);

    List<OpenPlayerEntity> selectPlayers();

    long getTotalPlayer();

    OpenPlayerEntity selectByplayerNo(String playerCode);

}