package com.efida.sports.dmp.dao.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.efida.sports.dmp.dao.entity.OpenCallLogEntity;

public interface OpenCallLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_call_log
     *
     * @mbggenerated
     */
    int insert(OpenCallLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table open_call_log
     *
     * @mbggenerated
     */
    int insertSelective(OpenCallLogEntity record);

    /**
     * 查询日志
     * @title
     * @methodName
     * @author wangyi
     * @description
     * @return
     */
    List<OpenCallLogEntity> selectByUnitCode(Map<String, Object> params);

    /**
     * 查询日志
     * @title
     * @methodName
     * @author wangyi
     * @description
     * @param callLogId
     * @param unitCode
     * @return
     */
    OpenCallLogEntity selectByIdAndUnitCode(@Param(value = "callLogId") Long callLogId,
                                            @Param(value = "unitCode") String unitCode);

}