package com.efida.sports.dmp.dao.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.efida.sports.dmp.dao.entity.ReportMatchFinishEntity;

public interface ReportMatchFinishEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_match_finish
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_match_finish
     *
     * @mbggenerated
     */
    int insert(ReportMatchFinishEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_match_finish
     *
     * @mbggenerated
     */
    int insertSelective(ReportMatchFinishEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_match_finish
     *
     * @mbggenerated
     */
    ReportMatchFinishEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_match_finish
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportMatchFinishEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_match_finish
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportMatchFinishEntity record);

    /**
     * 
     * 根据matchCode 和   partTimeDay 查询报名人数
     * @param map
     * @return
     */
    List<ReportMatchFinishEntity> queryMatchFinishByCode(Map<String, Object> map);

    /**
     * 根据matchCode获取官方完赛数
     * 
     * @param map
     * @return
     */
    Map<String, Object> officialMatchFinishCount(Map<String, Object> map);

    /**
     * 根据matchCode获取官方完赛数
     * 
     * @param matchCode
     * @return
     */
    List<Map<String, Object>> queryALLofficialMatch(@Param(value = "matchCode") String matchCode);

    /**
     * 根据matchCode获取官方完赛数
     * 
     * @param map
     * @return
     */
    List<Map<String, Object>> organizerMatchFinishCount(Map<String, Object> map);

    /**
     * 查询总完赛数
     * 
     * @return
     */
    Map<String, Object> countFinishMatchByParams(Map<String, Object> map);

}