package com.efida.sports.dmp.biz.score;

import java.util.List;
import java.util.Map;

import com.efida.sports.dmp.dao.entity.ReportUnitFinishEntity;

/**
 * 承办方完赛人数统计
 * 
 * @author zengbo
 * @version $Id: ReportUnitFinishService.java, v 0.1 2018年8月30日 上午9:15:37 zengbo Exp $
 */
public interface ReportUnitFinishService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_unit_finish
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_unit_finish
     *
     * @mbggenerated
     */
    int insert(ReportUnitFinishEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_unit_finish
     *
     * @mbggenerated
     */
    int insertSelective(ReportUnitFinishEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_unit_finish
     *
     * @mbggenerated
     */
    ReportUnitFinishEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_unit_finish
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportUnitFinishEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_unit_finish
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportUnitFinishEntity record);

    /**
     * 保存多个承办方完赛统计数据
     * 
     * @param records
     */
    void saveReportUnitFinishList(List<ReportUnitFinishEntity> records);

    /**
     * 根据条件获取承办方总完赛人数
     * 
     * @param startTime
     * @param endTime
     * @return
     */
    int countTotalUnitFinish(String startTime, String endTime);

    /**
     * 根据条件查询承办方完善人数
     * 
     * @param map
     * @return
     */
    List<Map<String, Object>> countUnitFinishByParams(String startTime, String endTime,
                                                      String likeParams, String inParams);

    /**
     * 根据unitCode获取承办方完赛人数
     * 
     * @param map
     * @return
     */
    int officialMatchFinishCount(String unitCode);

}
