package com.efida.sports.dmp.biz.score;

import java.util.List;
import java.util.Map;

import com.efida.sports.dmp.dao.entity.ReportMatchFinishEntity;

/**
 * 
 * 
 * @author zengbo
 * @version $Id: ReportMatchFinishService.java, v 0.1 2018年8月30日 上午9:59:58 zengbo Exp $
 */
public interface ReportMatchFinishService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_match_finish
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_match_finish
     *
     * @mbggenerated
     */
    int insert(ReportMatchFinishEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_match_finish
     *
     * @mbggenerated
     */
    int insertSelective(ReportMatchFinishEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_match_finish
     *
     * @mbggenerated
     */
    ReportMatchFinishEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_match_finish
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportMatchFinishEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_match_finish
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReportMatchFinishEntity record);

    /**
     * 保存多個賽事完成人數統計
     * 
     * @param records
     */
    void saveReportMatchFinishList(List<ReportMatchFinishEntity> records);

    /**
     * 根据matchCode获取官方完赛数
     * 
     * @param map
     * @return
     */
    int officialMatchFinishCount(String matchCode);

    /**
     * 查询所有完赛数据
     * 
     * @return
     */
    List<ReportMatchFinishEntity> queryAllData();

    /**
     * 获取官方完赛数据
     * 
     * @param matchCode
     * @return
     */
    List<Map<String, Object>> queryALLofficialMatchByCode(String matchCode);

}
