package com.efida.sports.cert.dao.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.efida.sports.cert.dao.entity.ScoreCertEntity;

public interface ScoreCertEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_cert
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_cert
     *
     * @mbggenerated
     */
    int insert(ScoreCertEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_cert
     *
     * @mbggenerated
     */
    int insertSelective(ScoreCertEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_cert
     *
     * @mbggenerated
     */
    ScoreCertEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_cert
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ScoreCertEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_cert
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ScoreCertEntity record);

    /**
    /**
     *  String unitCode
     *  String idempotentId
     *  
     * @return
     */
    ScoreCertEntity selectByIdempotentId(Map<String, Object> map);

    /**
     * 获取用户最新未查看的证书
     * 
     * @param registerCode
     * @return
     */
    ScoreCertEntity getRegisterNewestScoreCert(String registerCode);

    /**
     * 修改证书查看状态 （修改为已查看）
     * 
     * @param certCode
     */
    void updateViewScorePicStatus(String certCode);

    /**
     * 查询用户证书
     * 
     * @param registerCode
     * @return
     */
    List<ScoreCertEntity> getRegisterScoreCerts(String registerCode);

    /**
     * 获取需要生成证书数据
     * 
     * @return
     */
    List<ScoreCertEntity> selectNeedGenPic();

    /**
     * 获取证书
     * 
     * @param certSn
     * @return
     */
    ScoreCertEntity getScoreCertByCertSn(@Param(value = "certSn") String certSn);

    /**
     * 获取并实现锁证书
     * @title
     * @methodName
     * @author wangyi
     * @description
     * @param id
     * @return
     */
    ScoreCertEntity lockScorecertById(@Param(value = "id") long id);
}